### ISSUE TITLE
Purgecss seems not working

### ISSUE THREAD

**Issue by steven0811** [nuxt-community/tailwindcss-module#100]
### Version
@nuxtjs/tailwindcss: v2.0.0
nuxt: v2.12.2

### Steps to reproduce
1. Migrate 1.4.1 to 2.0.0 follow this [link](https://github.com/nuxt-community/tailwindcss-module/blob/master/lib/templates/tailwind.config.js)
![Screen Shot 2020-05-05 at 6 08 26 PM](https://user-images.githubusercontent.com/4948562/81055519-6cb5a300-8efb-11ea-9753-d54bc0a3f8e5.png)

2. npm run build

### What is actually happening?
Tailwind CSS seems like not be purged.
![Screen Shot 2020-05-05 at 6 07 42 PM](https://user-images.githubusercontent.com/4948562/81055550-80610980-8efb-11ea-9ac9-0de9ce61b2ea.png)

**Comment by aaronhuisinga** [comment]
@steven0811 @Atinux it actually seems like in my case after updating to v2.0.0 our custom config file isn't being read at all.

**Comment by Atinux** [comment]
You confirm that you use `extractCSS`?

I don't know if Tailwind v1.4.0 PurgeCSS works with extractCSS, could you try without it?

**Comment by subdesign** [comment]
Am I right, if I have some unused css classes in my eg. index.vue file, purge should remove them?
Because reading all "purge not works" fresh issues and build up the setup following the recommendations, all unused classes remain there. For example the .subtitle class which comes with the base nuxt install.

**Comment by idflood** [comment]
I was having issue configuring purgecss to work with nuxt, and the nuxt-purgecss plugin [mentionned here](https://purgecss.com/guides/nuxt.html#nuxt-js-plugin) was throwing errors in the build.

Evenutally I resolved it by **not using** the `nuxt-purgecss` module, and instead use the [tailwind own purgecss](https://github.com/nuxt-community/tailwindcss-module/blob/master/lib/templates/tailwind.config.js) as mentionned in the first comment.

Also, I'm using the nuxt extractCSS, and one option to extract the css as one file only:

nuxt.config.js:

```javascript
  build: {
    extractCSS: true,
    // this is not required, output as one css file instead of one by page.
    optimization: {
      splitChunks: {
        cacheGroups: {
          styles: {
            name: 'styles',
            test: /\.(css|vue)$/,
            chunks: 'all',
            enforce: true
          }
        }
      }
    },
```

tailwind.config.js
```javascript
{
  ...,
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js'
    ],
    options: {
      whitelist: [
      ],
      whitelistPatternsChildren: [
      ]
    }
  }
}
```
