### ISSUE TITLE
nuxt config.css priority High than module config

### ISSUE THREAD

**Issue by Ncaffeine** [nuxt-community/tailwindcss-module#107]
Config nuxt.config.js css option.
My css option value is

`
export default {
 css: ['a.css', 'tailwind.css']
}
`

But in runtime 'tailwind.css' priority High than 'a.css'. it will override 'a.css' same css rule.
because tailwindcss-module auto insert 'tailwind.css' in head for config.css value 

So i suggest : nuxt config.css priority High than module config. when config.css has 'tailwind.css'. module will skip css insert option.

**Comment by Atinux** [comment]
Actually you should not set the `tailwind.css` since the module add it for you, see https://github.com/nuxt-community/tailwindcss-module/blob/master/lib/module.js#L26

**Comment by Ncaffeine** [comment]
> Actually you should not set the `tailwind.css` since the module add it for you, see https://github.com/nuxt-community/tailwindcss-module/blob/master/lib/module.js#L26

But i want 'a.css' css rule priority High than 'tailwind.css' css rule.

**Comment by sei-jdshimkoski** [comment]
@Atinux Is there any way to disable the auto-injection of the `tailwind.css` file?

Injecting before all other CSS is a nice feature but I've run into times when it needs to come **after** all other CSS declared in the global CSS config.

It'd be nice to be able to disable auto-injection and manually include it.

**Comment by sei-jdshimkoski** [comment]
Looking at the code, I guess I could try to set the cssPath config option to `null`, then just manually add the `tailwind.css` file in the `nuxt.config.js` CSS option.

Will give that a try and see what happens.

**Comment by sei-jdshimkoski** [comment]
Well, that was a complete failure. Was worth a shot but hacky anyway.

Hopefully, a future version of this will enable the ability to disable auto-injection of the `tailwind.css` file.

**Comment by Atinux** [comment]
What about having `cssPath: false` to disable adding the CSS?

This could be done easily with a PR @sei-jdshimkoski

**Comment by sei-jdshimkoski** [comment]
That would be rad.
