### ISSUE TITLE
default setting is not working

### ISSUE THREAD

**Issue by xerosanyam** [nuxt-community/tailwindcss-module#112]
### Version
@nuxtjs/tailwindcss: latest
nuxt: latest

### Steps to reproduce
just install the plugin as mentioned

### What is Expected?
the tailwind css styles are applied

### What is actually happening?
the styles are getting applied in dev, but not in prod

**Comment by devanandb** [comment]
@xerosanyam Looks like by default all the classes not included in any of your pages, are being purged. It didnt work for me, because, I am setting those classes dynamically, so quick fix was to just include them somewhere.

**Comment by xerosanyam** [comment]
Thanks for replying @devanandb. How do I include them?

**Comment by xerosanyam** [comment]
added to whitelist 
![image](https://user-images.githubusercontent.com/3167278/82556965-658fc580-9b88-11ea-8ccd-53a8785df830.png)
