### ISSUE TITLE
at-rule or selector expected css / VS Code

### ISSUE THREAD

**Issue by web2033** [nuxt-community/tailwindcss-module#115]
VS Code is yelling at me when writing `@apply` rule:

![2020-05-27_100955](https://user-images.githubusercontent.com/11320080/82988880-8467df00-a002-11ea-82b6-0acff5f9ad60.jpg)

Where to look?

**Comment by bramburn** [comment]
Add Lang=“postcss” to the style tag

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by web2033** [comment]
Thanks!
