### ISSUE TITLE
Wich version of tailwind has the module? 1.4 or 1.4.5

### ISSUE THREAD

**Issue by IsidroMar95** [nuxt-community/tailwindcss-module#117]
The latest version of tailwind is the 1.4.5 however this module indicates that it is 1.4 so I don't know if it's 1.4.5 or stayed in the 1.4

**Comment by bramburn** [comment]
Looking at 

`"tailwindcss": "^1.4.0"`
the carret states minor or patch updates
so if you run [yarn upgrade](https://classic.yarnpkg.com/en/docs/cli/upgrade-interactive/) it should help upgrade to 1.4.5. If tailwindcss still works then leave it as is until you're ready to do an upgrade.
