### ISSUE TITLE
PostCSS scoped has no effect

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/tailwindcss-module#119]
```html
<template>
  <div class="classname">
    <div>item 1</div>
    <div>item 1</div>
  </div>
</template>

<style lang="postcss" scoped>
.classname {
  @apply flex items-center;
}
</style>
```

Has no effect, until i remove `scoped`. Is this a bug?

**Comment by mornir** [comment]
In my case, when adding or removing the `scoped` attribute, I need to do a full page refresh to see the changes.

**Comment by Atinux** [comment]
Hi @webcoderkz 

It should work with no issue normally, can you confirm the bug with the v3 of this module?

**Comment by webcoderkz** [comment]
@Atinux it does work now, i dunno, maybe v3 fixed this issue.
