### ISSUE TITLE
Nuxt Fatal Error

### ISSUE THREAD

**Issue by issyah** [nuxt-community/tailwindcss-module#121]
I've used Nuxt.js with @nuxtjs/tailwindcss a couple of projects before. However, when I tried installing @nuxtjs/tailwindcss on a new project today, this happen: 

`
 FATAL  Unexpected token {                                                                                                 16:21:28

  } catch {
  ^

  SyntaxError: Unexpected token {
  at Object.Module._extensions..js (module.js:663:10)
  at Object.Module._extensions..js (module.js:663:10)`

### Version
@nuxtjs/tailwindcss: ^2.0.0
nuxt: v2.12.2

### Steps to reproduce

- npx create-nuxt-app <project> 
- use TailwindCss as UI Framework 
- run npm run dev 

I've tried installing a new nuxt app without the framework and installing @nuxtjs/tailwindcss manually, still, the same issue persists. Nuxt.js works when I remove @nuxtjs/tailwindcss under the buildModules at nuxt.config.js

**Comment by mornir** [comment]
What Node version do you use? Could you try again with Node v12.
The "Optional catch binding" was relatively recently added to Node.

**Comment by issyah** [comment]
@mornir Hi, thanks for your comment. I was running Node v8. I've upgraded and fortunately, it did work now! Thank you! Will close this issue.
