### ISSUE TITLE
Rename default file to tailwind.postcss

### ISSUE THREAD

**Issue by Akryum** [nuxt-community/tailwindcss-module#126]
### Is your feature request related to a problem? Please describe.

The `css` extension is used for `assets/css/tailwind.postcss` file generated by the plugin and used by default. The thing is, using postcss syntax like `@apply` will result in VS Code errors since the IDE thinks it's a plain standard CSS file.

![image](https://user-images.githubusercontent.com/2798204/85223015-e75d5380-b3bf-11ea-8ada-ab6a41c87b07.png)

### Describe the solution you'd like

Rename the default file to `tailwind.postcss`

### Describe alternatives you've considered

Rename the default file to `tailwind.pcss`

### Workaround

In `nuxt.config.js`:

```js
  tailwindcss: {
    cssPath: '~/assets/css/tailwind.postcss',
  },
```

**Comment by Maiquu** [comment]
You can add this to VS Code `settings.json` as a workaround:
```json
"files.associations": {
    "*.css": "postcss"
}
```

**Comment by Atinux** [comment]
This would become a breaking change and will be for `v3`

**Comment by Atinux** [comment]
Actually V3 will not create the CSS file anymore, so you can directly configure the `cssPath` option to link to the PostCSS file :)

**Comment by hacknug** [comment]
Can confirm this seems to be working as expected. Thank you for the changes on v3 ❤️
