### ISSUE TITLE
Backquote (`) purge issue

### ISSUE THREAD

**Issue by voraczech** [nuxt-community/tailwindcss-module#129]
### Version
@nuxtjs/tailwindcss: v1.4.1
nuxt: v2.13.3

### Steps to reproduce

Purge module can't process backquotes, so for example this code will be processed:

```html
<button :class="[isSomeVariable && 'bg-red-600 hover:bg-red-500 focus:border-red-700 active:bg-red-700', /* something else */ >
```

On the other hand, this will fail (using backquotes - `):

```html
<button :class="[isSomeVariable && `bg-red-600 hover:bg-red-500 focus:border-red-700 active:bg-red-700`, /* something else */ >
```

### What is Expected?

The former and the later should behave equally.

### What is actually happening?

They don't.

I'm not really sure if this issue is related only to this module implementation or Purge module itself, so please, be kind if this is not related, thank you 😌.

**Comment by Atinux** [comment]
Hi @voraczech 

Can you please upgrade to the v2 of this module and see if it works please?

**Comment by ludo237** [comment]
It might still be a problem if you use backtick on computed method for retrieving classes.

Basically this does not work

```js
computed: {
    colorClasses () {
      return [
        `bg-${this.color}-100`,
        `dark:bg-${this.color}-200`,
        `border-${this.color}-400`,
        `dark:border-${this.color}-500`,
        `text-${this.color}-700`,
        `dark:text-${this.color}-800`,
      ];
    },
  },
```
