### ISSUE TITLE
2.1.0 introduces Full Static Build Error (Out of Memory)

### ISSUE THREAD

**Issue by jhull** [nuxt-community/tailwindcss-module#132]
Upgrading to `2.1.0` killed my static builds. Downgrading back to `1.0.0` solved my issues.

This is a large app with over 1200 pages, and while I've seen similar errors here: [OOM Error](https://github.com/nuxt/nuxt.js/issues/7262), [#5931](https://github.com/nuxt/nuxt.js/issues/5931) and [nuxt-community/auth-module#286 (comment)](https://github.com/nuxt/nuxt.js/issues/5931), neither of them provided a viable solution short of producing a repro - which is not feasible given the nature of the error. 

The error in question: 

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by Atinux** [comment]
Sadly I think this is related to Tailwind Purge CSS system, I don't know what I can do regarding this :(

**Comment by jhull** [comment]
Turns out it was a Node problem. For anyone having memory leak issues with super giant sites. Adding this:

```
[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
```

To my `netlify.toml` file fixed everything.
