### ISSUE TITLE
Add `darkMode` option

### ISSUE THREAD

**Issue by Atinux** [nuxt-community/tailwindcss-module#135]
### Is your feature request related to a problem? Please describe.

The integration with tailwindcss-dark-mode with @nuxtjs/color-mode is not great, as well with the Tailwind Typography plugin.

### Describe the solution you'd like

Supporting the `darkMode: true` option to add our dark mode plugin we use [here](https://github.com/nuxt/content/blob/dev/packages/theme-docs/src/tailwind.config.js#L156-L179).

**Comment by divine** [comment]
Tailwindcss has now experimental dark mode https://github.com/tailwindlabs/tailwindcss/pull/2279

I think this might be easier to implement.

Thanks!

**Comment by Atinux** [comment]
Indeed, at first we need to update the `@nuxtjs/color-mode` package to support the new Tailwind option to customize the class.

**Comment by Atinux** [comment]
Since Tailwind v1.8+ supports dark mode now and @nuxtjs/color-mode v1.1.0 is out, no need to have such feature now :)
