### ISSUE TITLE
Broken sandbox for Tailwind UI Example

### ISSUE THREAD

**Issue by cogor** [nuxt-community/tailwindcss-module#136]
### Version
@nuxtjs/tailwindcss: 3.0.0
nuxt: 2.14.1

### Reproduction Link
https://tailwindcss.nuxtjs.org/examples-tailwindui
https://codesandbox.io/s/nuxt-tailwindui-xy1jk?from-embed

### Steps to reproduce
1. Open link
2. Done, you're awesome ;)

### What is Expected?
Working sandbox

### What is actually happening?
Need installed dependency `v-click-outside`

**Comment by divine** [comment]
FYI, additional error  `WARN  No provided fonts.` related to google fonts module.

**Comment by Atinux** [comment]
Fixes, thank you!
https://codesandbox.io/s/nuxt-tailwindui-xy1jk
