### ISSUE TITLE
Markdown files not getting taken into account by purgecss

### ISSUE THREAD

**Issue by saturnonearth** [nuxt-community/tailwindcss-module#139]
### Version
@nuxtjs/tailwindcss: 3.0.0
nuxt: 2.14.1

### Reproduction Link
https://codesandbox.io/s/divine-leftpad-jhgml?file=/nuxt.config.js

When using target: 'static', classes are being purged when viewing with `nuxt start` for markdown files.

### What is Expected?
Classes that are used in the markdown files in a div are not purged.

### What is actually happening?
Markdown files are not getting taken into account by purgecss

**Comment by Atinux** [comment]
Hi @saturnonearth 

You need to add your Markdown files to the `purge.content` option in your `tailwind.config.js`:

```js
module.exports = {
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'content/**/*.md'
    ]
  }
}
```

The @nuxt/content module will push it in the next release to avoid adding it manually :)
