### ISSUE TITLE
CSS assets bundled with app.js adding to bundle size

### ISSUE THREAD

**Issue by amerkay** [nuxt-community/tailwindcss-module#143]
Great work! Fantastic module.

I'm using nuxt v2.14.1 with tailwindcss-module v3.0.0. 

I have `extractCSS` set to `false`. I'm seeing the css inline in the `<head>` section, but, it's also bundled in app.js. 

Is there a way to keep critical css inlined, but exclude it from the app.js bundle to minimize bundle size? Thanks!

![image](https://user-images.githubusercontent.com/3519378/90020017-c2d67700-dc9e-11ea-9649-78188228b893.png)

**Comment by Atinux** [comment]
Hi @amerkay 

It is necessary to be included in the JavaScript so Nuxt can inline it when doing the server-side rendering.
