### ISSUE TITLE
Tailwind 1.7.3 Release

### ISSUE THREAD

**Issue by mkalayci35** [nuxt-community/tailwindcss-module#147]
Please update [tailwind css 1.7.3](https://github.com/tailwindlabs/tailwindcss/releases)

**Comment by mathieutu** [comment]
Am I wrong saying that the module require tailwindcss `^1.6.2`, so you just can update the version yourself, by updating your node_modules? 🤔

**Comment by mkalayci35** [comment]
> Am I wrong saying that the module require tailwindcss `^1.6.2`, so you just can update the version yourself, by updating your node_modules? 🤔 
> 
> 
> 
> 

Yes :)

**Comment by nathanhenniges** [comment]
It does work what you must do is remove tailwindcss from  /node_modules/ and also package-lock.json then run `npm i` again and it should install the latest version.

**Comment by swsalim** [comment]
> It does work what you must do is remove tailwindcss from /node_modules/ and also package-lock.json then run `npm i` again and it should install the latest version.

This works for me 🍺

**Comment by mathieutu** [comment]
Yeah, actually my question was rhetorical.
It works perfectly as it, and has nothing to do with this package. Please read the npm and yarn documentation. (And actually no need to remove anything, a simple `yarn upgrade` do the job (and surely something equivalent for npm))

@Atinux maybe a note in the readme can be good, or there is a chance we'll have new issues and PR to update for each new version Adam tags.

**Comment by Atinux** [comment]
Just released `v3.0.1` as well as adding the note in the docs: https://tailwindcss.nuxtjs.org/setup/#upgrading-tailwind

Thank you @mathieutu
