### ISSUE TITLE
PostCss plugins are not added in tailwindcss styles

### ISSUE THREAD

**Issue by nandes2062** [nuxt-community/tailwindcss-module#154]
According to the nuxt documentation in the section [https://nuxtjs.org/guides/configuration-glossary/configuration-build#postcss-plugins--nuxt-tailwindcss ](https://nuxtjs.org/guides/configuration-glossary/configuration-build#postcss-plugins--nuxt-tailwindcss ) does not generate the postcss plugins fallbacks in tailwind styles, for example by adding a plugin like 'postcss-custom-properties':
in development looks like this:
```
.text-secondary {
     color: var(--secondary-color);
}
```
doing nuxt build should generate the static Hex fallback:
```
.text-secondary {
    color: #f8c400; // does not generate the postcss fallback in tailwind
    color: var(--secondary-color);
}
```

Help me please, solution to apply Postcss on tailwindCSS styles in Nuxt.js?

**Comment by Atinux** [comment]
Hi @nandes2062 

Can you please create a reproduction on CodeSandbox please?

**Comment by dexcell** [comment]
@Atinux 
the repro is pretty simple, you just add any postcss plugins such as `postcss-rename` in nuxt.config.js
e.g.
<img width="652" alt="Screen Shot 2020-10-18 at 16 28 38" src="https://user-images.githubusercontent.com/41800/96363504-0b0e8b80-115f-11eb-946e-dc72b3040a87.png">

then run `npm run generate`,
tailwind css doesn't get renamed, which tell us that the postcss plugin doesn't run on tailwind modules.
while nuxt css get renamed.

**Comment by nandes2062** [comment]
I solved it this way, and it works ...

`
// In nuxt.config.js
import { join } from 'path'

export default {
  ...
  buildModules: [
    // Doc: https://github.com/nuxt-community/nuxt-tailwindcss
    '@nuxtjs/tailwindcss'
  ],

  build: {
    postcss: {
      plugins: {
        tailwindcss: join(__dirname, 'tailwind.config.js'),
        'postcss-custom-properties': {},
        cssnano: {
          preset: 'default'
        }
      },
      preset: {
        autoprefixer: {}
      }
    }
  }
}`
