### ISSUE TITLE
Tailwind module broken when required from another module.

### ISSUE THREAD

**Issue by adamemrts** [nuxt-community/tailwindcss-module#155]
### Version
@nuxtjs/tailwindcss: v3.0.1
nuxt: v2.14.3

### Steps to reproduce
Use tailwind inside module as:
```
this.requireModule(['@nuxtjs/tailwindcss', {
  configPath: '../module/tailwind.config.js',
  cssPath: '../module/assets/css/tailwind.css'
}])
```
Where paths are relative or absolute to the project using module.

### What is Expected?
Tailwind should work same as when configured in `nuxt.config.js`.

### What is actually happening?
In logs it looks like Tailwind is loading but styles are absent in the browser.
```
ℹ Using Tailwind CSS from ~/../module/assets/css/tailwind.css             nuxt:tailwindcss 10:02:52
ℹ Merging Tailwind config from ~/../module/tailwind.config.js             nuxt:tailwindcss 10:02:52
```

**Comment by Atinux** [comment]
Hi @adamemrts 

We actually use `nuxt.resolver.resolveAlias` (https://github.com/nuxt-community/tailwindcss-module/blob/master/lib/module.js#L18), I recommend you to give an absolute path for the `configPath` and `cssPath`.

Also, you can directly give the configuration as object, see https://tailwindcss.nuxtjs.org/tailwind-config#config-option

**Comment by adamemrts** [comment]
I've tried to give absolute path and also tried to use config instead of configPath. Unfortunately none of them changed anything and still didn't gave any CSS to the browser - only unstyled HTML - when tailwind module was registered from other module.

Will try do make reproducible repo example after work.
