### ISSUE TITLE
HMR not working when marking changes in tailwind.config.js

### ISSUE THREAD

**Issue by chrispreisler** [nuxt-community/tailwindcss-module#157]
Hey guys,
I think I found a HMR bug.

### Version
@nuxtjs/tailwindcss: 3.0.1
nuxt: 2.14.0

### Reproduction Link
https://codesandbox.io/s/cocky-water-uc4qt?file=/pages/index.vue

I created a tailwind.config.js and set a color value. I added to the headline "The Coldest Sunset" a class "text-bug". So the headline shows in red. When you change the value to blue in the tailwind.config.js, nothing happens.

<img width="1113" alt="Bildschirmfoto 2020-08-25 um 12 02 58" src="https://user-images.githubusercontent.com/5261762/91161427-07b0d380-e6cb-11ea-9116-bd5694da28a9.png">

### Expected Result
Before 3.0.0 I could make changes to the tailwind.config.js and then after some time the changes are shown in dev mode. Now nothing happens. I always have to restart the dev environment (yarn dev).

Do I miss any option to enable that or is this a bug since 3.0.0?

Thank you very much for your help in advance.

Best regards
Chris

**Comment by Atinux** [comment]
Hi @chrispreisler 

This is fixed with https://github.com/nuxt-community/tailwindcss-module/commit/8c26472031d10400d829200fd6d65f0306ab442d

Released with v3.0.2 :)

**Comment by chrispreisler** [comment]
Wow that was fast. Thank you very much for your fast help. :)

**Comment by DanjBethel** [comment]
@Atinux experiencing this now in 5.3.3. editing nuxt.config.ts doesn't restart the server. has to be manually ended and restarted.

**Comment by Atinux** [comment]
What version of Nuxt are you using?

**Comment by richi-dev** [comment]
@Atinux I got the same problem.

"@nuxtjs/tailwindcss": "6.2.0"
"nuxt": "3.0.0"

Installed by `npx nuxi init <project-name>` and `npm install --save-dev @nuxtjs/tailwindcss`

**Comment by ylhuang-richi** [comment]
@Atinux  I got the same problem.

"@nuxtjs/tailwindcss": "6.2.0"
"nuxt": "3.0.0"

Installed by `npx nuxi init <project-name>` and `npm install --save-dev @nuxtjs/tailwindcss`

**Comment by davidwebca** [comment]
I'm experiencing this as well, I've never had it work, but in my case there's a full page reload of the browser, the change seems to be detected by the module because I see logs in the command line while I'm developing, but the changes in the config file are not taken into account and the only way to have them work is to fully kill the dev task and start again.

**Comment by ineshbose** [comment]
Hey - this issue was brought up again in #682 and we reworked the module to fix this. Please test your project with 6.12.0 and if issue persists, we can continue discussion in #682. 🙂
