### ISSUE TITLE
Module doesn't work when required from other module and server host set to '0.0.0.0'

### ISSUE THREAD

**Issue by adamemrts** [nuxt-community/tailwindcss-module#158]
### Version
@nuxtjs/tailwindcss: v3.0.1
nuxt: v.2.14.1

### Reproduction Link
This bug occurs ONLY on LOCAL enviroment, doesn't apply to codesandbox - need to download and run locally.
https://codesandbox.io/s/nuxt-tailwind-module-sdcuk

### Steps to reproduce
1. Add simple `module.js` which requires tailwind module:
```
module.exports = function (moduleOptions) {
  this.requireModule("@nuxtjs/tailwindcss")
}
```
2. Add this module to nuxt.config.js:
```
modules: [
  { handler: require('./module.js') }
]
```
3. Add server host configuration option to nuxt.config.js
```
server: {
  host: '0.0.0.0'
}
```

### What is Expected?
Tailwind module should work, css should be added to the webpage.

### What is actually happening?
Tailwind module doesn't work, there is no css added to the webpage.

**Comment by Atinux** [comment]
Hi @adamemrts 

Sorry for the late answer, actually `requireModule` returns a `Promise`, so make sure to actually `await` it in your `module.js`:

```js
module.exports = async function (moduleOptions) {
  await this.requireModule("@nuxtjs/tailwindcss");
};
```

See your sandbox fixed: https://codesandbox.io/s/nuxt-tailwind-module-forked-9x8c8?file=/module.js
