### ISSUE TITLE
Tailwind v1.8.6 Release

### ISSUE THREAD

**Issue by mkalayci35** [nuxt-community/tailwindcss-module#163]
Please update [Tailwind Css 1.8.6](https://github.com/tailwindlabs/tailwindcss/releases/tag/v1.8.6).

Thank you

**Comment by ludo237** [comment]
From the docs:

> When a new version of Tailwind CSS is released, you don't need to wait for this module to upgrade, you can directly upgrade your dependencies.

Please read the documentation next time

**Comment by mkalayci35** [comment]
> Please read the documentation next time

I know these. But I wrote to let the team know.

**Comment by ludo237** [comment]
That makes 0 sense but ok

**Comment by manniL** [comment]
As @ludo237 explained, there is no re-release of the module necessary. New installations will come with the newest tailwind version and people already using the module can update easily 😋

Thanks anyway 👍🏻
