### ISSUE TITLE
.css included in the main nuxt bundle? why?

### ISSUE THREAD

**Issue by OfekA** [nuxt-community/tailwindcss-module#165]
I've looked around for an answer for this but couldn't find one, I can see that in the main bundle some of the tailwind.css is included: 
![image](https://user-images.githubusercontent.com/1408457/93221096-03318500-f776-11ea-9749-dc58f054d092.png)
The snippet with some of the css in the file itself.
![image](https://user-images.githubusercontent.com/1408457/93221225-2825f800-f776-11ea-8ece-221cd4a1528b.png)

When I run Nuxt in analyze mode I can see that it takes 4.28KB Gzipped in the main bundle, why does this happen? my CSS is usually loaded in the head of the page.

**Comment by Atinux** [comment]
Hi @OfekA 

Actually it is necessary to have it in the JS to be able to server-render it for any page.

This is his Nuxt (and vue server renderer) handles CSS actually.

**Comment by OfekA** [comment]
Thanks for the answer @Atinux 😄
