### ISSUE TITLE
Nuxt-Tailwind browser freezes when inspecting elements and modifying styles(ALL BROWSERS(relevant) TESTED)

### ISSUE THREAD

**Issue by TNortnern** [nuxt-community/tailwindcss-module#167]
### Version
@nuxtjs/tailwindcss: 3.0.2
nuxt: 2.14.5

### Reproduction Link

Clone: https://github.com/TNortnern/Provisionade-fe

### Steps to reproduce
Literally on any browser, inspect a element on the home page and uncheck a fews styles then try to go inspect another element, uncheck it's style, eventually it will freeze upon unchecking some elements styles and won't allow you to inspect or change styles for a few seconds.

### What is Expected?
For the browser to not freeze for 5 seconds when trying to do browser styling

### What is actually happening?
It's just freezing, I made a gif [here](https://streamable.com/ozbr02) to better demonstrate.

**Comment by TNortnern** [comment]
After further testing, it just seems like the tailwind/ui plugin is the root cause

**Comment by TNortnern** [comment]
To anyone experiencing the bug, it's best to just integrate tailwindcss yourself for now. It fixes the issue, something is up with this module because on dev it comes out to about 1GB with the module but with manually adding tailwind it's about 400mb.

**Comment by Atinux** [comment]
Hi @TNortnern 

Do you use the default configuration for the module?

**Comment by TNortnern** [comment]
@Atinux Yes I did. Fresh nuxt-tailwind installation

**Comment by Atinux** [comment]
@TNortnern I tried locally but could not reproduce this bug, do you have any informations about your computer?

**Comment by gino** [comment]
I have the same issue. I have a custom Tailwind configuration file though, but my whole tab also freezes when I use Chrome Devtools to update anything.

**Comment by defusevenue** [comment]
I'm having this issue as well. The following fix from Tailwindcss issue did not work for me.

```css
/*! @import */
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Did anyone find a workaround to this issue?

**Comment by gino** [comment]
> I'm having this issue as well. The following fix from Tailwindcss issue did not work for me.
> 
> ```css
> /*! @import */
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 
> Nuxt is reporting an impressive 1.09GB of memory usage. Did anyone find a workaround to this issue?

I can confirm that the problem still exists after trying `/*! @import */`, and the memory usage is indeed pretty high... :/

**Comment by TNortnern** [comment]
Looks like the issue was due to tailwind as @gino said. If you just upgrade your tailwind to latest this issue will dissapear.

**Comment by TNortnern** [comment]
Looks like this issue is back with nuxt/tailwind v4
