### ISSUE TITLE
config file is gone

### ISSUE THREAD

**Issue by adhamfarrag** [nuxt-community/tailwindcss-module#173]
Hi, just tried to create a new nuxt app, and realized that assets/css/main.css and tailwind config files are gone. I can understand why main.css is gone but was it intentional to get rid of config file ? 

Tailwind CSS IntelliSense doesn't work unless tailwind.config.js is in workplace. 

My nuxt and tailwind module versions are: 

`
    "nuxt": "^2.14.5",
    "@nuxtjs/tailwindcss": "^3.0.2",
`

Thanks

**Comment by Atinux** [comment]
Hi @adhamfarrag 

This is intentional, but you can always create an empty `tailwind.config.js` file if you want IntelliSense to work :)
