### ISSUE TITLE
Support function call in user defined tailwind.config.js

### ISSUE THREAD

**Issue by f3l1x** [nuxt-community/tailwindcss-module#185]
### Prologue

At this moment, there could be file `{project}/tailwind.config.js` which is merged with other default tailwind config and `nuxt.tailwindcss` defined in `nuxt.config.js`.

Default tailwind.config.js provided by this module exposes config behind function call. 

https://github.com/nuxt-community/tailwindcss-module/blob/f40d95b8c7348e9ae830b2eee23f3e727eba858a/lib/files/tailwind.config.js#L1

It would be great to have this option also for user defined file `{project}/tailwind.config.js`. At this time, it accept only object.

https://github.com/nuxt-community/tailwindcss-module/blob/f40d95b8c7348e9ae830b2eee23f3e727eba858a/lib/module.js#L30-L37

### Is your feature request related to a problem?

I think it's not a problem.

### Describe the solution you'd like

I would prepare PR with test if user provided `{project}/tailwind.config.js` returns object or function. 

### Describe alternatives you've considered

Do nothing.

### Additional context

Good job so for guys. Thx.

**Comment by Atinux** [comment]
Thank you for the idea @f3l1x 

What I am afraid of is that the user `tailwind.config.js` will not be standard as Tailwind but specific to Nuxt and I wanted to avoid this. What happends the day Tailwind decided that you can export a function in your `tailwind.config.js`?

I believe Nuxt users should use the [tailwindcss.config](https://tailwindcss.nuxtjs.org/tailwind-config#config-option) instead.

**Comment by f3l1x** [comment]
Yup, no problem, I understand. :-) Have a nice day.
