### ISSUE TITLE
How to pass Tailwind styles to iFrame?

### ISSUE THREAD

**Issue by pgvlas** [nuxt-community/tailwindcss-module#191]
I need to have styled components in the iFrame. 

My code looks like this:

`<iframe srcdoc="<button class="bg-white p-4 mr-2">Sample button</button>"></iframe>`

Do you have any idea how to pass generated Tailwind styles to have buttons in the iFrame styled as well? :)
I wonder if we can add something like <style src="PATH_TO_GENERATED_STYLES" /> but I'm not sure what is the generated path in Nuxt application.

**Comment by Atinux** [comment]
I actually have no idea sorry

**Comment by pgvlas** [comment]
So for now, I found in the Sources tab of the developer tools base.css file created by Tailwind. In `tailwind.config.js` I added these lines to reduce file size:

```
purge: {
  enabled: true,
}
```

I used it only to build styles on dev, then commented it out for dev perfomance. After that I just copied base.css content to new file in `/static/iframe.css` and then included these styles in iframe like that:

```
<iframe
  ref="iframe"
  :srcdoc="previewHtml"
  class="w-full"
/>
...
previewHtml: `
    <html class="h-full">
      <head><link href="/iframe.css" rel="stylesheet"></head>
      <body class="antialiased h-full">
        BODY
      </body>
    </html>
`
```

That's my solution for now where you have to rebuild and copy styles every time after new classes are added. I will close issue but if anyone get a better idea, feel free to reopen :)

**Comment by gregorvoinov** [comment]
Hi, do you found a better solution since November? Running into the same problem and also only come up with this solution.

**Comment by pbshgthm** [comment]
I'm having a similar requirement. Is there an update on this issue?

**Comment by paulwongx** [comment]
Same issue. I wish there was some info on it online...

**Comment by maxPugh** [comment]
Adding

`<script src="https://cdn.tailwindcss.com"></script>` 

to my srcDoc string has worked for me

**Comment by gregorvoinov** [comment]
@maxPugh This will only add the default styles, anything custom will not be included...

**Comment by pbshgthm** [comment]
Currently, I've set it up this way, and it works well. I'm using Vite as my build tool.

```ts
import styles from '../../tailwind.css?inline'

const initialContent = (
  `<!DOCTYPE html>
    <html>
      <head>
        <style>
          ${styles}
        </style>
      </head>
      <body>
        <div id="page" class="page"></div>
      </body>
    </html>`
)
```

**Comment by Oudwins** [comment]
@aboveyunhai This works for both development and production? It will break if nextjs changes the way it handles stylesheets right? Have you found any issues with the code so far? Is there anything missing?

**Comment by aboveyunhai** [comment]
> @aboveyunhai This works for both development and production? It will break if nextjs changes the way it handles stylesheets right? Have you found any issues with the code so far? Is there anything missing?

Yes, it will fail if next.js change the way it handles stylesheets. The better way would be using a cli to generate an individual minified css file that we have for tailwind in production, then pass that css file into the iframe, but I didn't try it out though. 
It means either you generate it manually or create that file before production build
https://tailwindcss.com/docs/optimizing-for-production
something like `'build": "tailwind-create-minified-file-command-here && next build"`
