### ISSUE TITLE
global variants not working

### ISSUE THREAD

**Issue by jinusean** [nuxt-community/tailwindcss-module#195]
### Version
 @nuxtjs/tailwindcss@3.2.0
nuxt@2.14.7

### Steps to reproduce
My  `tailwindlconfig.js` is:
```
module.exports = {
  variants: ['responsive', 'hover', 'focus', 'group-hover'],
}
```

I expected `group-hover` variants to be applied globally, but it is not. 

The variants config property only works if I update each style individually like this:
```
module.exports = {
  variants: {
    opacity: ['responsive', 'hover', 'focus', 'group-hover'],
    transform: ['responsive', 'group-hover'],
  },
}
```

**Comment by Atinux** [comment]
Actually, this is related to Tailwind documentation: https://tailwindcss.com/docs/pseudo-class-variants#app
