### ISSUE TITLE
Upgrade tailwind 2.0.1

### ISSUE THREAD

**Issue by apithy-isidro-martinez** [nuxt-community/tailwindcss-module#202]
Please upgrade to version 2.0.1 which has just been released

**Comment by web2033** [comment]
Note - it requires at least Node.js 12.13.0
https://tailwindcss.com/docs/upgrading-to-v2#upgrade-to-node-js-12-13-or-higher

**Comment by apithy-isidro-martinez** [comment]
@web2033 i know, i tried this https://tailwindcss.nuxtjs.org/setup/#upgrading-tailwind but the version still in `1.9.6`

**Comment by malalecherocks** [comment]
Same here, updated Node to latest version, and I can't upgrade tailwind to 2.0.1, any news? Doc says: just use npm update to update to latest version of tailwind... :(

**Comment by apithy-isidro-martinez** [comment]
@Atinux i tried but i got this error
![Screenshot_1](https://user-images.githubusercontent.com/74619952/99586752-c10f0480-29ad-11eb-920e-30792c14f802.png)

**Comment by ThomOrlo** [comment]
@apithy-isidro-martinez https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by tapitapeh** [comment]
Hi, I got this error
```
Module build failed (from ./node_modules/postcss-loader/src/index.js):                                                                                                                            friendly-errors 05:08:57
TypeError: getProcessedPlugins is not a function
```

![Frame 11](https://user-images.githubusercontent.com/7647443/99589097-7ed5d980-2a26-11eb-9416-bcef7406cd55.jpg)

I'm using npm and this also happens when I tried to fresh install with npm init nuxt-app

**Comment by apithy-isidro-martinez** [comment]
@ThomOrlo worked out doing this `npm uninstall tailwindcss postcss autoprefixer` and then `npm install tailwindcss@latest postcss@latest autoprefixer@latest` but anyway I hope the module will be updated

**Comment by malalecherocks** [comment]
Hi I did that, but this is the error I got:

`MacBook-Pro-de-Oscar:project oscar$ npm uninstall tailwindcss postcss autoprefixer

removed 5 packages, and audited 2261 packages in 4s

71 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
MacBook-Pro-de-Oscar:project oscar$ npm install tailwindcss@latest postcss@latest autoprefixer@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: tailwindcss@2.0.1
npm ERR! node_modules/tailwindcss
npm ERR!   tailwindcss@"2.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^1.0" from @tailwindcss/custom-forms@0.2.1
npm ERR! node_modules/@tailwindcss/custom-forms
npm ERR!   @tailwindcss/custom-forms@"^0.2.1" from @tailwindcss/ui@0.6.2
npm ERR!   node_modules/@tailwindcss/ui
npm ERR!     @tailwindcss/ui@"^0.6.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/oscar/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oscar/.npm/_logs/2020-11-18T21_47_57_866Z-debug.log
MacBook-Pro-de-Oscar:project oscar$ `


any idea? I can install first the postcss and autoprefixer itself ok, but when I try to install tailwindcss@latest, the error is the same... help please :(

**Comment by malalecherocks** [comment]
Looks like tailwindui is no longer needed acording to ui doc, so I uninstalled it and now looks it's working, thanks anyway.

**Comment by apithy-isidro-martinez** [comment]
@malalecherocks in the colors do you see the `50` values ? i.e `bg-gray-50` not to me and I don't know why

**Comment by malalecherocks** [comment]
I was just seeing that haha, I need to check if they have limited the colors and you have to add the palettes? something like that? I'm checking it right now

**Comment by moritzruth** [comment]
In a fresh Nuxt.js project with `@nuxtjs/tailwindcss` it was sufficient to run `yarn add tailwindcss@compat`.

**Comment by apithy-isidro-martinez** [comment]
@malalecherocks if you figured out let me know pls

**Comment by malalecherocks** [comment]
@apithy-isidro-martinez in your tailwind.config.js you need to add the colors you want to use in your project...


// tailwind.config.js
const colors = require('tailwindcss/colors')
module.exports = {
  future: {},
  purge: [],
  theme: {
    extend: {},
    colors: {
      gray: colors.blueGray,
      coolgray: colors.coolGray,
      blue: colors.blue,
      red: colors.rose,
      pink: colors.fuchsia,
      green: colors.green,
    }
  },
  variants: {},
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
  ],
}

all of this I found in the official doc,

**Comment by sduduzog** [comment]
Looks like it was picked up by @renovate-bot  but tests are failing in CI https://github.com/nuxt-community/tailwindcss-module/pull/201

**Comment by jpokan** [comment]
> In a fresh Nuxt.js project with `@nuxtjs/tailwindcss`, it was sufficient to run `yarn add -D tailwindcss@compat`.

Tried it, got it working. But it seems to take longer to compile and it is using lots of RAM. Have you noticed it or its just me
![Screenshot 2020-11-19 031700](https://user-images.githubusercontent.com/8276144/99639531-b4be9200-2a15-11eb-824c-79f287923947.png)
?

**Comment by tommypratama** [comment]
In the meantime, it seems like using the `@nuxtjs/tailwindcss` module isn't a good idea. Try the following:

- Install nuxt without the `@nuxtjs/tailwindcss` module
- `yarn add -D tailwindcss@compat`
- `npx tailwindcss init`

Done, you can use all the features in Tailwind v2

**Comment by web2033** [comment]
@Atinux Am I right, that if you use custom TW config, than this module doesn't help much?
(It was make sense for me when Nuxt created config files for TW, but then you removed that feature...)

**Comment by sduduzog** [comment]
I got my existing project by installing both tailwindcss and postcss as dev dependencies, Allthough I did notice slower build times. Just do:
```
npm install --save-dev postcss tailwindcss@latest
```

**Comment by victorgarciaesgi** [comment]
Tailwind v2 is using PostCss 8, Nuxt is using PostCss 7. I think we have to use the compat build

https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by Atinux** [comment]
I added a note how to upgrade to TailwindCSS 2 in the docs: https://tailwindcss.nuxtjs.org/setup#tailwind-2

Also, I have to wait for CodeSandBox to upgrade to Node 12 for the examples since it is still using Node 10.

**Comment by Atinux** [comment]
> @Atinux Am I right, that if you use custom TW config, than this module doesn't help much?
> (It was make sense for me when Nuxt created config files for TW, but then you removed that feature...)

Would be nice if you read the docs before writing such comments: https://tailwindcss.nuxtjs.org/tailwind-config

This module adds:
- Sensible defaults for purging your files
- Ability to extend the tailwind config with hooks and a merging strategy (before Tailwind introduced `extends`)
- Add the possibility to access the Tailwind configuration with tree-shaking

**Comment by victorgarciaesgi** [comment]
@Atinux Is Postcss 8 support in the works for Nuxt 2.x or will it release with Nuxt 3?

**Comment by Icesofty** [comment]
Thank you for the updated Doc, really useful in dev mode.
I'll wait until V2.15 (BTW, do you have a release date?) for prod, in the meantime I'm going to use the CDN in the Header, not the best thing to do but I need the 2.0 Tailwind's functionality.

**Comment by jankal** [comment]
@Atinux please be aware that installing the tailwind compatibility build creates a hiccup with npm (`npm@6.14.8`).

Situation:
```
"tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1",
"@nuxtjs/tailwindcss": "^3.1.0",
"nuxt": "^2.14.6"
"postcss": "^7.0.35",
"autoprefixer": "^9.8.6",
```

NPM resolves a tree and ends up with the following (`npm list tailwindcss`):
```
+-- @nuxtjs/tailwindcss@3.3.1
| `-- tailwindcss@1.9.6
`-- tailwindcss@npm:@tailwindcss/postcss7-compat@2.0.1
```

Based on the tailwindcss `package.json` in both builds, there should be two binaries in `node_modules/.bin/`: `tailwindcss` & `tailwind`. But there are none.

Sidenote: JetBrains IDEs since 2020.3 need these binaries to provide autocomplete. That's how I figured it out.

Yarn does it "better". At least those two binaries are in fact there. Running the `tailwindcss` command points out, that it in fact is the binary of `@tailwindcss/postcss7-compat 2.0.1`.

Yarn seems to resolve the same tree (concerning the relationship of these 3 packages):
```
├─ @nuxtjs/tailwindcss@3.3.1
│  └─ tailwindcss@1.9.6
└─ tailwindcss@2.0.1
```

I don't think we can fix this issue here, as long as `@nuxtjs/tailwindcss` v4 is out. If this is an issue, you can only use yarn for now.

**Comment by apithy-isidro-martinez** [comment]
> > In a fresh Nuxt.js project with `@nuxtjs/tailwindcss`, it was sufficient to run `yarn add -D tailwindcss@compat`.
> 
> @moritzruth Tried it, got it working. But it seems to take longer to compile and it is using lots of RAM. Have you noticed it or its just me?
> 
> ![Screenshot 2020-11-19 031700](https://user-images.githubusercontent.com/8276144/99639531-b4be9200-2a15-11eb-824c-79f287923947.png)
> 
> **Edit:** Figure out it was because new Tailwind 2 was heavier with new defaults, so it was increasing the build time. To optimize it during development, you can disable some Tailwind features you don't plan to use in your tailwind.config.js file.

How did you solve that? It seems to take more than 1 minute to build and consumes a lot of RAM
![Screenshot_1](https://user-images.githubusercontent.com/74619952/101952798-d5b27700-3bbe-11eb-8bff-3d34febb6840.png)

**Comment by jpokan** [comment]
@apithy-isidro-martinez So, in my tailwind.config.js file I defined only the features or in this case colors I intended to use and not extend it:
In this example just using transparent and yellow colors.
```
const colors = require('tailwindcss/colors')
module.exports = {
  theme: {
    colors: {
      transparent: 'transparent',
      pink: colors.yellow,
    }
  }
}
```
You might want to check https://tailwindcss.com/docs/configuration and https://tailwindcss.com/docs/optimizing-for-production#limiting-your-color-palette for better understanding.
Also, when I upgraded to version >3.3.3 of @nuxt/tailwindcss , I noticed a faster build time.

**Comment by m2sahin** [comment]
Hello, when will this update.  Please provide an exact date.

**Comment by manniL** [comment]
> 
> 
> Hello, when will this update. Please provide an exact date.

This is already possible (see https://github.com/nuxt-community/tailwindcss-module/issues/202#issuecomment-738835586)

**Comment by martinnacimiento** [comment]
> > Hello, when will this update. Please provide an exact date.
> 
> Using Tailwind 2.x is already possible (see [#202 (comment)](https://github.com/nuxt-community/tailwindcss-module/issues/202#issuecomment-738835586))

This is not possible for me, I deploy with `npm run generate` but not have any Tailwind 2 feature are available.

**Comment by bmulholland** [comment]
I believe v4 closes this out @pi0

**Comment by davodaslanifakor** [comment]
when we can use  tailwind 3 in nuxt/tailwind? @Atinux
