### ISSUE TITLE
Extend Variants not working

### ISSUE THREAD

**Issue by duthanhduoc** [nuxt-community/tailwindcss-module#206]
**Version**
```
"@nuxtjs/tailwindcss": "^3.1.0",
"nuxt": "^2.14.6"
```
This is my `tailwind.config.js` file
```
module.exports = {
  variants: {
    extend: {
      display: ['hover', 'focus'],
    },
  },
}
```
I add variants but i can not see `hover:block` or `hover:hidden` in my classes. `hover:block` not working.
My `tailwind.config.js` file works because i use corePlugins, it works 
```
 corePlugins: {
   // ...
  display: false,
}
```

**Comment by whardier** [comment]
I'm having a similar issue working with opacity: ['disabled'] not working as well.  I'm doing the best I can to make sure that the contents of the application are scanned properly.

**Comment by whardier** [comment]
As it happens.. It turns out that TailwindCSS 1.9.5 is brought in via @nuxtjs/tailwindcss

I resolved my problem by reading the docs for V1 of TailwindCSS (no extend in variants.. just explicit preferences):

https://v1.tailwindcss.com/docs/pseudo-class-variants#disabled

**Comment by egistli** [comment]
@whardier Oh man, thanks for pointing out that the version of tailwindcss is still 1.x!

**Comment by duthanhduoc** [comment]
> As it happens.. It turns out that TailwindCSS 1.9.5 is brought in via @nuxtjs/tailwindcss
> 
> I resolved my problem by reading the docs for V1 of TailwindCSS (no extend in variants.. just explicit preferences):
> 
> https://v1.tailwindcss.com/docs/pseudo-class-variants#disabled

Yep, Thank you. I think this issue is about version. I'll wait for the next version

**Comment by whardier** [comment]
I'm not sure if this is much of a thing yet: https://github.com/nuxt-community/tailwindcss-module/tree/feat/tailwindcss2

The diff doesn't look horrible: https://github.com/nuxt-community/tailwindcss-module/compare/feat/tailwindcss2

**Comment by whardier** [comment]
Also: https://tailwindcss.nuxtjs.org/setup/#tailwind-2
