### ISSUE TITLE
Missing Tailwind classes

### ISSUE THREAD

**Issue by mijorus** [nuxt-community/tailwindcss-module#211]
### Version
@nuxtjs/tailwindcss: 3.1.0
nuxt: 2.14

### Steps to reproduce
I noticed that some tailwind classes, specifically `text-opacity-75+` and `text-7xl+` don't work using nuxt-tailwind.
If I extend the configuration using `tailwind config`, they work just fine

### What is Expected?
Classes to be applied correctly

### What is actually happening?
Seems like those classes are missing.

**Comment by mijorus** [comment]
> What do you mean when you extend the configuration it works?

I mean that,  obviously,  if I extend the tailwind configuration using tailwind.config.js, adding the missing classes,  it works.

**Comment by qvdp** [comment]
These classes come from the new `2.0.1` release of tailwindcss, wich is not supported for the moment by nuxt-tailwind module.

You can refer to the previous version of the [documentation](https://v1.tailwindcss.com/docs/font-size#class-reference) to avoid the use of unsupported classes or import tailwindcss with a CDN to use new classes, waiting for the Nuxt 2.15 update.  🙂

**Comment by mijorus** [comment]
> These classes come from the new `2.0.1` release of tailwindcss, wich is not supported for the moment by nuxt-tailwind module.
> 
> You can refer to the previous version of the [documentation](https://v1.tailwindcss.com/docs/font-size#class-reference) to avoid the use of unsupported classes or import tailwindcss with a CDN to use new classes.  🙂
> 
> It seems you can also manually upgrade tailwindcss with a functional postcss, cf [nuxt tailwind docs](https://tailwindcss.nuxtjs.org/setup/#tailwind-2), waiting for the Nuxt 2.15 update. 
> ```
> yarn add --dev tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

Great.  Thank you
