### ISSUE TITLE
Nuxt can not detect the tailwind config --> can not use @apply the properties below the style 

### ISSUE THREAD

**Issue by harrytran998** [nuxt-community/tailwindcss-module#212]
### Version
```json
"@nuxtjs/tailwindcss": "^3.2.0",
"nuxt": "^2.14.7",
"autoprefixer": "^9",
"postcss": "^7",
"tailwindcss": "npm:@tailwindcss/postcss7-compat"
```

### Reproduction Link

https://github.com/harrytran998/reproduction-nuxt-tailwind

### Steps to reproduce
1,. Clone this repo
2. Yarn dev --> You will see the error

### What is Expected?
Nuxt & HRM can detect the tailwind config.

### What is actually happening?
In index.vue. I code like bellow and run `yarn dev`
```vue
<template>
  <div class="mt-8 xl:mt-28">
    <div id="home-call-action-1" class="flex mb-0 xl:mb-32 bg-gray-1 rounded-2xl xl:rounded-3xl">
      <div class="flex-1 -mr-8 xl:mr-0 p-4 xl:py-14 xl:px-16">
        <p class="p-4">asdasdasdsad</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style lang="scss" scoped>
#home-call-action-1 {
  p {
    @apply bg-gray-3;
  }
}
</style>
```
---> This error are presented.
![image](https://user-images.githubusercontent.com/24296018/100496375-3a64df00-3186-11eb-9c63-4c28b39337f6.png)

**And when start dev mode, I don't see the nuxt tailwind notify using tailwind.config.js(Merging Tailwind config from ...)**
![image](https://user-images.githubusercontent.com/24296018/100496000-1c49af80-3183-11eb-9fc9-5a283c304a8d.png)

**Comment by harrytran998** [comment]
My bad when use src dir but dont change the config dir of tailwind :v

**Comment by usman-web-dev** [comment]
@harrytran998 thanks mannnnn!!!!
