### ISSUE TITLE
Color list in tailwind 2

### ISSUE THREAD

**Issue by Zenthae** [nuxt-community/tailwindcss-module#218]
### Version
@nuxtjs/tailwindcss: 3.1.0
nuxt: 2.14.6
tailwindcss: 2.0.1

### Steps to reproduce
Default behavior 

### What is Expected?
all colors has to be displayed on `_tailwind` url

### What is actually happening?
some colors aren't displayed by default like `orange` and `teal`, their are disabled by default in tailwindcss now, you need to extends the config, so this is happening
[https://i.imgur.com/LLk0pAS.png](https://i.imgur.com/LLk0pAS.png)

**Comment by Zenthae** [comment]
updated to `v3.3.3` and still got the issue, so unless it broke between `v3.3.1` and `v3.3.3` it's wasn't fixed ^^

**Comment by Zenthae** [comment]
```js
const colors = require('tailwindcss/colors');

module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        orange: colors.orange,
      },
      boxShadow: {
        DEFAULT:
          '0 1px 3px 0 rgba(0, 0, 0, 0.1), 1px 1px 2px 0 rgba(0, 0, 0, 0.50)',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```
i added orange because it not added by default

**Comment by rogden** [comment]
@Atinux Tailwind has a resolveConfig and a flattenColorPalette function that may be helpful in parsing the colors. I use both in my [Tailwind Config Viewer](https://github.com/rogden/tailwind-config-viewer) project. See https://github.com/rogden/tailwind-config-viewer/blob/master/lib/tailwindConfigUtils.js#L2

**Comment by schneefux** [comment]
Still present in 3.4.1

**Comment by Zenthae** [comment]
@schneefux everything is working well, if you are talking about needing to import the colors, then it's not an issue, it was a choice from tailwind to remove them from the default colors. but you can always add them yourself. 

```js
const colors = require('tailwindcss/colors');

module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        // Add the colors you want
        orange: colors.orange,
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```
