### ISSUE TITLE
IE11 Syntax error on arrow function in config

### ISSUE THREAD

**Issue by snakemastr** [nuxt-community/tailwindcss-module#226]
Hello, I have a Nuxt project with @nuxtjs/tailwindcss module.
On IE11 I am getting a syntaxerror on the index page.
It points to webpack:///node_modules/tailwindcss/stubs/defaultConfig.stub.js
```
    backgroundColor: theme => theme('colors'),
```
I know arrow functions are not supported by IE11 but I don't get why this part is referred to on the production environment, as this is a devDependency and buildModule and I would expect this code not being loaded at all on the production environment.

**Comment by snakemastr** [comment]
Oh wow, I am kinda stupid :(
I just found that I am actually resolving the theme to refer to screen breakpoints in the code
```
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '~/tailwind.config.js';

const {theme} = resolveConfig(tailwindConfig);

if (window.innerWidth < parseInt(theme.screens.lg)) {
  window.addEventListener('scroll', this.onScroll);
 } else {
   window.removeEventListener('scroll', this.onScroll);
}
```
Is there a better way to solve this? I would love to keep using the config variables and I thought resolveConfig would handle this. (I am aware TailwindCSS has limited support for IE)

**Comment by Geminii** [comment]
I think you will need to prepare yourself for the future : https://tailwindcss.com/docs/upgrading-to-v2#support-for-ie-11-has-been-dropped 😅

**Comment by snakemastr** [comment]
@Atinux so I should use exposeConfig instead of resolveConfig? I don't know how I got to the code of resolveConfig but as it worked for FF, Chrome and Edge I didn't care much untill the client wanted IE11 support

@Geminii Well, I am all about the future as it comes to development, sadly our clients are not. This is really one of the downsides when developing for a broad audience: all the people that think "The internet" means Internet Explorer have to be kinda supported too

**Comment by Atinux** [comment]
Yes @snakemastr 
We created exposeConfig so it faster, lighter and IE compatible than resolveConfig of Tailwind

**Comment by Geminii** [comment]
@snakemastr Yes unfortunatly ... 
But IE 11 will end to August 17th, 2021 so we can keep hope that the logic of clients will evolve in this direction to migrate to Edge 😀
