### ISSUE TITLE
Cannot find module 'tailwindcss/colors'

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt-community/tailwindcss-module#228]
### Version
@nuxtjs/tailwindcss: 3.3.4
nuxt: 2.14.6

### Steps to reproduce
`yarn create nuxt-app some-app-name`
Leave all blank and select tailwind css as ui framework.
Following the official tailwind documentation, add tailwind.config.js with the following to enable all colors (works in tailwind playground):
```
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    colors: {
      ...colors
    }
  },
  variants: {},
  plugins: [],
}

```
The package.json:
```
{
  "name": "some-app-name",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "nuxt": "^2.14.6"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^3.3.4"
  }
}
```

### What is Expected?
All colors should be available.

### What is actually happening?
Yarn displays an error : `Cannot find module 'tailwindcss/colors'`

**Comment by florian-lefebvre** [comment]
No, I thought it was the default version with the new version of the module. I'll try that tomorrow.

**Comment by florian-lefebvre** [comment]
It works now. Thank you!

**Comment by siba2893** [comment]
Hey what was the issue?

**Comment by florian-lefebvre** [comment]
Hey @siba2893 ! I was assuming that the default version of Tailwind CSS was >=2.0 at the time. This is now the case.

**Comment by jcjiron** [comment]
I have same issue and my version is  "tailwindcss": "3.3.5"

**Comment by florian-lefebvre** [comment]
Please open a new issue, context was really different in 2021
