### ISSUE TITLE
Purging wrong component

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/tailwindcss-module#229]
### Version
@nuxtjs/tailwindcss: ^3.1.0
nuxt: latest

### Steps to reproduce
I am pulling in https://www.npmjs.com/package/vue-tailwind-modal however once deployed, the purgecss has removed styling for the modal.

Not sure how I can tell this package to not ignore the CSS of https://www.npmjs.com/package/vue-tailwind-modal

**Comment by Geminii** [comment]
Hi @simplenotezy 

To avoid purge on some classes, you can add the `purge` property into `tailwind.config.js` like this : 

```js
purge: {
    options: {
       whitelist: ['yourClass']
    },
}
```

Hope this help you 😀

**Comment by simplenotezy** [comment]
Hi @Geminii thanks for your reply.

This config ended up fixing it:

```
module.exports = {
	variants: {
		extend: {
			// ...
			borderColor: ['hover', 'active', 'focus']
		}
	},
	purge: {
		content: ['./node_modules/vue-tailwind-modal/src/VueTailwindModal.vue'],
		options: {
			// Include the bg-smoke for use when css is compressed
			// see: https://tailwindcss.com/docs/controlling-file-size
			whitelist: ['bg-smoke-800']
		}
	}
}

```
