### ISSUE TITLE
tailwindViewer not working

### ISSUE THREAD

**Issue by emilsgulbis** [nuxt-community/tailwindcss-module#235]
### Version
`nuxt: 2.14.7`,
`@nuxtjs/tailwindcss: 3.4.0`

### Reproduction Link
https://codesandbox.io/s/young-dawn-6s5r5

### Steps to reproduce
Install latest `@nuxtjs/tailwindcss`

### What is Expected?
`/_tailwind` to show tailwindViewer page

### What is actually happening?
Throws error: `Unexpected token {`
On local machine: `Cannot use import statement outside a module`

**Comment by shealan** [comment]
I'm getting the same "Cannot use import statement outside a module" error on Nuxt 2.14.12 and @nuxtjs/tailwindcss 3.4.0

**Comment by ttkoma** [comment]
Same issue. Im attach stack
![image](https://user-images.githubusercontent.com/1864455/102553818-898e9780-40d4-11eb-94d1-14af3601a9b8.png)

**Comment by reslear** [comment]
ping respected @Atinux look here please, thx)

<img width="660" alt="Снимок экрана 2020-12-18 в 02 28 23" src="https://user-images.githubusercontent.com/12596485/102555864-b5ac1780-40d8-11eb-822c-3e0fe915dd79.png">

**Comment by pi0** [comment]
It seems an issue with esm package resolving serverMiddleware. @reslear meanwhile would you please try setting `createRequire: 'jiti'` option in nuxt.config?

**Comment by reslear** [comment]
https://github.com/nuxt-community/tailwindcss-module/issues/235#issuecomment-747776258 respected @pi0 very thx for fast answering )

sorry but, this option show same errors

i cleaned node_modules package-lock and .cache (https://github.com/nuxt-contrib/jiti/issues/9)
install you interest pkg `jiti` and set `createRequire: 'jiti'` on `nuxt.config.ts`

more info 
* node v12.16.3
* @nuxt/typescript-runtime 2.0.0

exist other solutions or wait merging you fast fix https://github.com/nuxt-community/tailwindcss-module/pull/236 ?

**Comment by Franco-Chan** [comment]
Same here...
