### ISSUE TITLE
Broken image link in Tailwind UI CodeSandbox example

### ISSUE THREAD

**Issue by mvllow** [nuxt-community/tailwindcss-module#242]
There is a broken image link in the CodeSandbox on [examples/tailwindui](https://tailwindcss.nuxtjs.org/examples/tailwindui). I was unable to find a way to contribute a fork in CodeSandbox, but swapping the logo is all that's needed:

**`pages/index.vue:11`**

```diff
- src="https://tailwindui.com/img/logos/workflow-mark-on-dark.svg"
+ src="https://tailwindui.com/img/logos/workflow-mark-indigo-400.svg"
```

**Comment by Geminii** [comment]
Hi @mvllow 👋 

Thanks for the feedback 😀
Indeed you can't because the CodesanSandbox is on the @Atinux account. 
He is the only one who can fix it 😊
