### ISSUE TITLE
Tailwind height breakpoints missing in v3.1.0

### ISSUE THREAD

**Issue by ljdatasci** [nuxt-community/tailwindcss-module#245]
I created a nuxtjs app with tailwind css and I noticed that the height breakpoints for h-52 and h-72 to h-96 are missing.  When I view the tailwind-config-viewer I don't see them listed.  I'm using nuxtjs/tailwindcss v3.1.0 with nuxtjs v 2.14.6.  Are they not available in this version of nuxt/tailwind?

**Comment by Geminii** [comment]
Hi @ljdatasci 👋 

`h-52 h-72 h-96` are new height class added in Tailwindcss version 2. 
currently on nuxt tailwindcss module, it use version 1.9 but you can already use the version 2 if you follow [the setup](https://tailwindcss.nuxtjs.org/setup/#tailwind-2) then you could use these classes 😀

Note: `tailwind-config-viewer` is an additionnal UI project added to the tailwindcss module. 
currently use the version 1 : 
see : https://github.com/rogden/tailwind-config-viewer/blob/master/package.json#L61
