### ISSUE TITLE
Tailwind CSS IntelliSense Extension not working!

### ISSUE THREAD

**Issue by anburocky3** [nuxt-community/tailwindcss-module#247]
I also generated the `tailwind.config.js` but still it's not working.. Why is that?

**Comment by Geminii** [comment]
> I also generated the `tailwind.config.js` but still it's not working.. Why is that?

I don't understand the problem you are having because the problem is located on the IntelliSense plugin. 
Or do you create `tailwind.config.js` and this one isn't apply to your nuxt project 🤔 
I'm using Tailwind CSS IntelliSense Extension on my vscode and i don't have any project about it.

**Comment by anburocky3** [comment]
> > I also generated the `tailwind.config.js` but still it's not working.. Why is that?
> 
> I don't understand the problem you are having because the problem is located on the IntelliSense plugin.
> Or do you create `tailwind.config.js` and this one isn't apply to your nuxt project 
> I'm using Tailwind CSS IntelliSense Extension on my vscode and i don't have any project about it.

Using tailwindcss-module in your nuxt problem? I'm having problem with the intellisense, the classes names are not suggesting for me.

**Comment by Geminii** [comment]
Default classes or you extend some of them ? Can you provide screen or your config ? 
Need more information for help

**Comment by anburocky3** [comment]
Not extending, using the inbuilt default.

Here is the `tailwind.config.js`
```js
module.exports = {
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js',
      // TypeScript
      'plugins/**/*.ts',
      'nuxt.config.ts'
    ]
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}

```

**Comment by anburocky3** [comment]
Tried restarting the VSCode, Still the same problem. 

As a workaround, I installed it: https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion and it was working after a couple of mins.

Is it a bug? @Atinux

**Comment by Bluskript** [comment]
I have the same issue.

**Comment by anburocky3** [comment]
I'm not using any import inside the `tailwind.config.js` just using the default config file. but still experiencing the problem :/

**Comment by Bluskript** [comment]
Look at the VSCode's Output tab for the tailwind autocomplete plugin. That gives some useful info.

**Comment by f3ltron** [comment]
I have the same issue a lot. I have to deactivate and reactivate the plugins every time. I don't know if it's related to the module

**Comment by anburocky3** [comment]
There is no output logs. But it's not working either.. :/ I'm using this extension in order to work.
https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion

**Comment by jamiecarter7** [comment]
I'm having a similar issue, though its a great way to really learn the syntax it makes it a little less fun to use.

**Comment by jamiecarter7** [comment]
I created the app from scratch using the nuxt create and selecting the
tailwindCSS option.

But the intellisense is not working since I set up the project.

I have tried to look through the nuxt folder for the base tailwind files
but I am unable to find any files to look at.

The tailwind classes are working! It's purley that the intellisense is not
working.

**Comment by jamiecarter7** [comment]
Ok, that fixed my issue! :)

Thank you!

Is this a step I missed in the setup process?

**Comment by anburocky3** [comment]
As a temporary fix: Do the following, until they fix the problem:

1. Create **tailwind.config.js** file or better do `npx tailwind init` in your terminal, it should create **tailwind.config.js**
2. Restart the VSCode. Now it should work. :)

**Comment by IgnisDa** [comment]
> As a temporary fix: Do the following, until they fix the problem:
> 
> 1. Create **tailwind.config.js** file or better do `npx tailwind init` in your terminal, it should create **tailwind.config.js**
> 2. Restart the VSCode. Now it should work. :)

This is not an issue. The tailwind css VSCode extension is activated only if it detects a `tailwind.config.js` in the workspace. Once it detects it, just restart VSCode for the changes to take effect.

**Comment by anburocky3** [comment]
> > As a temporary fix: Do the following, until they fix the problem:
> > 
> > 1. Create **tailwind.config.js** file or better do `npx tailwind init` in your terminal, it should create **tailwind.config.js**
> > 2. Restart the VSCode. Now it should work. :)
> 
> This is not an issue. The tailwind css VSCode extension is activated only if it detects a `tailwind.config.js` in the workspace. Once it detects it, just restart VSCode for the changes to take effect.

If we want the tailwind css intellisense support we have to do the manual tweak(creating the `tailwind.config.js`) right. This workflow can be improved by nuxt or tailwind side :) That's my suggestion.

**Comment by IgnisDa** [comment]
IMO that workflow might be detrimental to others. For example, if I have the Tailwind extension installed but am not actually using tailwind in my project, the popups from the extension will only make it more difficult to code and create useless clutter. Moreover, since almost all projects need to define a custom `tailwind.config.js`, its really a non-issue.

> This workflow can be improved by nuxt or tailwind side

I agree with this. Maybe `yarn add --dev @nuxtjs/tailwindcss` can automatically setup a default file (for example run `tailwind init` under the hood?)

**Comment by theredfish** [comment]
I don't know exactly why but for information it doesn't work on the root node :
![image](https://user-images.githubusercontent.com/10638479/110180996-2545bf00-7e0b-11eb-8da7-cc59b51f59a3.png)

But works on children nodes :
![image](https://user-images.githubusercontent.com/10638479/110181042-38588f00-7e0b-11eb-87ea-37b35df150b8.png)

tailwindcss-intellisense output is ok : 
```
Found Tailwind config file: xxx/tailwind.config.js
Found tailwindcss v2.0.3: xxx/node_modules/tailwindcss
```

**Comment by saymo23** [comment]
I followed this guide but without installing nuxt with tailwind in the CLI, I installed it with npm and it worked for me.

https://tailwindcss.com/docs/guides/nuxtjs

**Comment by HusamIbrahim** [comment]
Was having this issue after an upgrade and it turned out that for some reason I was missing the `tailwindcss` module in my workspace. Got around it by installing it as a devDependency.

https://github.com/tailwindlabs/tailwindcss-intellisense#troubleshooting

**Comment by EMurrell** [comment]
I really struggled with this one, and tried so many suggested fixes.  At the end of the day, i installed the previous version of Tailwind CSS IntelliSense extension and now works fine.

**Comment by Asef00** [comment]
`npx tailwindcss init` worked out. But I already had a `tailwind.config.ts` file:
```
import { Config } from 'tailwindcss';

export default <typeof Config>{
  content: [],
  theme: {
    extend: {
      spacing: {
        '68': '17rem',
      },
      fontFamily: {
        'montserrat': 'Montserrat'
      },
      colors: {
        'bluegrey': '#9aabc5',
        'primary': '#3144c4'
      }
    },
  },
  plugins: [],
}
```
It means I need the one with the `.js` to show up IntelliSense.

**Comment by dvlden** [comment]
TailwindCSS extension for VS Code provides a settings option:
`tailwindCSS.experimental.configFile`, but unfortunately doesn't play well with `.ts` config.

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
```

So I suggest sticking with `tailwind.config.cjs`, it will work in a similar fashion.

**Comment by yousefomar724** [comment]
I found that Intellisense for the extension will not work with single quotes, If I use double quotes in my classNames, the intellisense works fine.

The solution for me was to update my settings.json to include "prettier.jsxSingleQuote": false,
  "prettier.singleQuote": false,

**Comment by mahendrameghwal** [comment]
![tw](https://user-images.githubusercontent.com/93032228/196499901-2eb47b3d-3cd9-4f64-be2d-8957482f3f18.JPG)


only  you just create empty this file your **Tailwind CSS IntelliSense** extension work properly

**Comment by wilfredinni** [comment]
Same issue with Nuxt 3 stable, nothing of the above works...

**Comment by wilfredinni** [comment]
> Same issue with Nuxt 3 stable, nothing of the above works...

I did a downgrade to version 0.9.1 and everything worked as expected

**Comment by Atinux** [comment]
Have you tried https://tailwindcss.nuxt.dev/tailwind/editor-support ?

**Comment by wilfredinni** [comment]
> Have you tried https://tailwindcss.nuxt.dev/tailwind/editor-support ?

Yes, but it was a bug with the tailwind intellisense plugin (I don't have the link right now), all worked out fine with version 0.9.1

**Comment by jamaluddinrumi** [comment]
> Have you tried https://tailwindcss.nuxt.dev/tailwind/editor-support ?

indeed, disabling .nuxt/tailwind.config.cjs & exclude .nuxt from intellisense inspection make it works

https://github.com/tailwindlabs/tailwindcss-intellisense/issues/663#issuecomment-1316788128

**Comment by huzaifahj** [comment]
It doesn't say anything about the above in the documentation

**Comment by ahmdsfdn** [comment]
> > Have you tried https://tailwindcss.nuxt.dev/tailwind/editor-support ?
> 
> indeed, disabling .nuxt/tailwind.config.cjs & exclude .nuxt from intellisense inspection make it works
> 
> ```
>   "tailwindCSS.files.exclude": [
>     "**/.git/**",
>     "**/node_modules/**",
>     "**/.hg/**",
>     "**/.svn/**",
> +   "**/.nuxt/**"
>   ]
> ```
> 
> [tailwindlabs/tailwindcss-intellisense#663 (comment)](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/663#issuecomment-1316788128)

it's work for my nuxt 3 project, ty
