### ISSUE TITLE
can't use @apply with custom utility in vue components

### ISSUE THREAD

**Issue by saemsev** [nuxt-community/tailwindcss-module#251]
### Version
Tailwind 2
@nuxtjs/tailwindcss: 3.4.2
nuxt: 2.14.12

### Notes

tailwind.scss 

```
@import 'custom/utilities.scss'
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

custom/utilities.scss
```
@layer utilities {
    .bg-foreground {
        @apply bg-white dark:bg-gray-800;
    }
}
```

index.vue 
```
<style lang="scss" scoped>
.mobile-search {
    @apply bg-foreground;
}
</style>
```

```
The `bg-foreground` class does not exist. If you're sure that `bg-foreground` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

I can't use @apply bg-foreground in my vue components, have I done something wrong?

**Comment by byshine** [comment]
It works for me without sass/scss out the box. Not sure if it helps you.

**Comment by talgat-ruby** [comment]
@s8v try https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports. Don't forget notes about `@import` and move all your `@tailwind` to separate files. See below in the link. Worked for me on React(CRA).

**Comment by ejirocodes** [comment]
Works in Vue 3 when I did 👇🏽 

`tailwind.config.js`
`ringColor: (theme) => ({
      DEFAULT: theme('colors.blue.500', '#2156C9'),
      ...theme('colors'),
      focus_border: '#2156C9',
    }),`



`tailwind.css`
`focus:ring-focus_border`

**Comment by Kcko** [comment]
> ### Version
> Tailwind 2 @nuxtjs/tailwindcss: 3.4.2 nuxt: 2.14.12
> 
> ### Notes
> tailwind.scss
> 
> ```
> @import 'custom/utilities.scss'
> @import 'tailwindcss/base';
> @import 'tailwindcss/components';
> @import 'tailwindcss/utilities';
> ```
> 
> custom/utilities.scss
> 
> ```
> @layer utilities {
>     .bg-foreground {
>         @apply bg-white dark:bg-gray-800;
>     }
> }
> ```
> 
> index.vue
> 
> ```
> <style lang="scss" scoped>
> .mobile-search {
>     @apply bg-foreground;
> }
> </style>
> ```
> 
> ```
> The `bg-foreground` class does not exist. If you're sure that `bg-foreground` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
> ```
> 
> I can't use @apply bg-foreground in my vue components, have I done something wrong?

I have same problem in my vue compoment.
Techstack: Vue 3, Tailwind 2.x.

Did you solve it somehow?
