### ISSUE TITLE
Assets/css/tailwind.css not generated

### ISSUE THREAD

**Issue by brandondeweese** [nuxt-community/tailwindcss-module#252]
The CSS is generated and placed within the <head> for some reason. I can get the config to work fine, but it simply doesn't generate a css file. I've combed over the docs and tried to generate different paths in the nuxt.config. Am I missing something simple here?

**Comment by munchy5132** [comment]
Same issue here

**Comment by EideWang** [comment]
same issue +1

**Comment by EtienneDion** [comment]
+1

**Comment by productfrontenddeveloper** [comment]
@munchy5132  @EideWang  @EtienneDion 

Can you please create a reproduction with CodeSandbox please? https://codesandbox.io/s/nuxt-tailwindcss-o4vn5pvp7q?from-embed

**Comment by ryanmstokes** [comment]
me too!

**Comment by ryanmstokes** [comment]
Here is a repro - https://codesandbox.io/s/cranky-cherry-oxkny?file=/pages/index.vue

no assets directory is generated as far as I can see!

**Comment by m-adil** [comment]
no assets directory got created for me too
