### ISSUE TITLE
Missing tailwind.css

### ISSUE THREAD

**Issue by sduncan-mbt** [nuxt-community/tailwindcss-module#253]
### Version
@nuxtjs/tailwindcss: "^3.4.2"
nuxt: "^2.14.12"

### Reproduction Link
https://github.com/sduncan-mbt/tailwind-test

### Steps to reproduce
npx create-nuxt-app tailwind-test
npm run dev
npx tailwindcss init
npm run dev

### What is Expected?
tailwind.css file created under /assets/css

### What is actually happening?
No File.

I've added images to the repo under /static/images that show the process I followed.

**Comment by sduncan-mbt** [comment]
Yes, I ran the init as when I ran `npm run dev` I didn't get a tailwind.css file created, which is the expected behaviour. Yes?

**Comment by sduncan-mbt** [comment]
Ok is this just a change in behaviour then as I just upgraded the version of `npx create-nuxt-app` I am using? 

I went to https://tailwindcss.com/docs/guides/nuxtjs when I had issue and the section......

"Open the ./assets/css/tailwind.css file that Nuxt.js generates for you by default and use the @tailwind directive to include Tailwind's base, components, and utilities styles, replacing the original file contents:"

made me think this was still the expected behaviour.

**Comment by sebmor** [comment]
+1 docs are not in sync to the current behavior. Tailwind.css is not created by default.

**Comment by bdrtsky** [comment]
Weird, I've created `tailwind.css` file, but injected one used instead. How do I use my own `tailwind.css`?

**Comment by ineshbose** [comment]
@bdrtsky please see cssPath in module options and docs!

**Comment by bdrtsky** [comment]
Also it seems if I put wrong path, it doesn't use it and no warning

```
tailwindcss: {
    cssPath: '~/assets/css/not-exist.css',
  },
```

**Comment by bdrtsky** [comment]
my bad @ineshbose I've used this module with Nuxt theme, that's why it failed to resolve 🤦‍♂️ I've fixed it with correct path
