### ISSUE TITLE
Tailwind dose not provide the rejected/purged style list  when using the `rejected` option of purgecss

### ISSUE THREAD

**Issue by majd-albandik** [nuxt-community/tailwindcss-module#254]
Hi,
in my project I am using nuxtjs with tailwind and I need somehow to get the purged style. 
I tried to use the `rejected` option (https://purgecss.com/configuration.html#options),  but don't know where to get the result
`tailwind.config.ts`  looks like this 
```
purge: {
    enabled: true,
    content: [
      './pages/**/*.vue',
      './components/**/*.vue',
      './layouts/**/*.vue',
      './plugins/**/*.vue',
      './plugins/**/*.ts',
    ],
    options: {
      rejected: true,
    },
 theme: {
  .......
```

so does anyone know how to solve this issue ? 
thanx

**Comment by majd-albandik** [comment]
@Atinux thank you for the fast replay 
https://githubbox.com/majd-albandik/tailwind-purgecss-unused-style-

**Comment by amjmhs** [comment]
I am interested in this, too! We have multiple developers and want to check the list of purged css-classes to avoid bugs in the application. Or at least, to have another tool for debugging bugs related to styling.

**Comment by amjmhs** [comment]
hey @Atinux , i guess our problem is that we just don't know how to retrieve this list after build. there is no example/documentation.

**Comment by majd-albandik** [comment]
@Atinux Exactly it is like, what @amjmhs said. 
It is just about how to log/store/retrieve the rejected css list. 
The documentation says 
When using postcss-purgecss-plugin, this list can logged via a postcss-reporter.

And when using the purgecss-webpack-plugin, it will be written in state data of webpack. 

I have tried both possibilites with nuxt/tailwindcss, but unfortuently I was not suceed to get the list.

**Comment by erNail** [comment]
@Atinux I have the same issue. I'm using `rejected: true`, and i don't know how to get the list of purged css classes.
