### ISSUE TITLE
Tailwind does not read CSS color variables

### ISSUE THREAD

**Issue by AlexSwtlsk** [nuxt-community/tailwindcss-module#258]
Hi,

I'm trying to get named colors working, by following this link https://tailwindcss.com/docs/customizing-colors#naming-your-colors

### Version
```json
  "dependencies": {
    "@vue/composition-api": "latest",
    "nuxt": "latest"
  },
  "devDependencies": {
    "@nuxt/types": "latest",
    "@nuxt/typescript-build": "latest",
    "@nuxtjs/tailwindcss": "^3.4.2",
    "autoprefixer": "^9",
    "postcss": "^7",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat"
  }
```

### Reproduction Link
[https://github.com/AlexSwtlsk/nuxt-composition-api-tailwind](https://github.com/AlexSwtlsk/nuxt-composition-api-tailwind)

### Steps to reproduce
- Init a new Nuxt project
- Install `nuxt tailwind` following https://tailwindcss.nuxtjs.org/setup/
- set variable colors in `@/assets/css/colors.css` following https://tailwindcss.com/docs/customizing-colors#naming-your-colors
- 
eg:
```
in @/assets/css/colors.css:
:root {
  --color-white: #fff;
  --color-black: #000;
…
}

in tailwind.config.js:
module.exports = {
  theme: {
    extend: {},
    fontFamily: false,
    colors: {
      black: "var(--color-black)",
      white: "var(--color-white)",
      "my-color": "var(--color-my-color)",
     …
    },
  },
  variants: {},
  plugins: [],
};
```
### What is Expected?
My CSS colors to be set and able to use `bg-my-color`

### What is actually happening?
Tailwind does not read the value of my variables, all colors set are empty/white, on the tailwind viewer and unusable in app

**Comment by nash403** [comment]
+1

I have the same issue ✋

**Comment by JacobGardos** [comment]
Make sure you include this in your nuxt.config.js. It tells tailwind where your colors.css is located via the cssPath property. 

```
tailwindcss: {
    cssPath: '~/assets/css/colors.css',
    configPath: 'tailwind.config.js',
    exposeConfig: false,
    config: {},
    injectPosition: 0,
  },
```


Here's the documentation which goes into more depth
https://tailwindcss.nuxtjs.org/options

**Comment by philipimperato** [comment]
I'm still having this issue:

`Internal server error: [postcss] ...\assets\css\components\_global.css:3:3: 'colors.primary' was found but does not resolve to a string. Did you mean something like 'colors.primary.50'?`

**Comment by MariuzM** [comment]
I'm having the same issue @AlexSwtlsk how did you resolve it?
