### ISSUE TITLE
dynamic classes with template string gets purged

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt-community/tailwindcss-module#259]
### Version
@nuxtjs/tailwindcss: 3.4.2
nuxt: 2.1412

### Reproduction Link
https://github.com/fabianwohlfart/test__tailwind-nuxt-template-string

### Steps to reproduce
install
run generate
run start
-> ./pages/index.vue

### What is Expected?
»test« is indented

### What is actually happening?
»test« is not indented, due to the lack of the »ml« classes

i guess its purgecss not tailwind who is responsible for this?
is there a workaround?
we have nested data, and i really would like to use a template string,
or should i do it somehow else?

**Comment by fabianwohlfart** [comment]
thanks for the quick reply.
ok, seems like we only have a manual solution here.
thanks!

**Comment by joshwcorbett** [comment]
Any chance a future update will address this?

**Comment by eladcandroid** [comment]
@Atinux Is it considered as a bug?

**Comment by Atinux** [comment]
I don't think no
