### ISSUE TITLE
Issue with PostCSS

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt-community/tailwindcss-module#261]
### Version
@nuxtjs/tailwindcss: ^3.4.2
nuxt: ^2.14.6
tailwindcss: npm:@tailwindcss/postcss7-compat
@tailwindcss/postcss7-compat: ^2.0.2
postcss: 7

### Reproduction Link
https://github.com/florian-lefebvre/portfolio/tree/v3_nuxtjs

### Steps to reproduce
```bash
$ yarn
$ yarn generate
```

### What is Expected?
A dist directory should be generated.

### What is actually happening?
There are errors in the terminal related with PostCSS version. Here is an example:
```bash
ERROR in ./node_modules/@nuxtjs/tailwindcss/lib/files/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/@nuxtjs/tailwindcss/lib/files/tailwind.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-purgecss requires PostCSS 8.
```

This doesn't happen with `yarn dev`.

**Comment by paulocastellano** [comment]
+1

**Comment by florian-lefebvre** [comment]
I removed the `@teamnovu/nuxt-breaky` package and it worked, so I'm going to open a issuethere.
