### ISSUE TITLE
Windi CSS (no longer required)

### ISSUE THREAD

**Issue by alexcroox** [nuxt-community/tailwindcss-module#264]
https://windicss.netlify.app/

For your consideration. Supposedly it drastically improves dev start up times which is a common problem when using Tailwind. 

https://twitter.com/antfu7/status/1361398324587163648

Edit: this may no longer be required due to improvements in core tailwind: https://github.com/nuxt-community/tailwindcss-module/issues/264#issuecomment-788351811

**Comment by alexcroox** [comment]
Further discussion here: https://github.com/nuxt-community/tailwindcss-module/pull/203

**Comment by ram-you** [comment]
> Any help is more than welcome

@antfu can you help please ?

**Comment by loonpwn** [comment]
Happy to take a look at this.

Any notes on implementation? Should we expect users to do the migration steps themselves? https://windicss.netlify.app/guide/migration.html#base-styles

**Comment by alexcroox** [comment]
Don't know if it helps but I'm also tracking nuxt-build-optimisations repo who are also looking to implement it automatically so that might help:

https://github.com/loonpwn/nuxt-build-optimisations/tree/feat/windycss

https://github.com/loonpwn/nuxt-build-optimisations/commits/feat/windycss

**Comment by alexcroox** [comment]
oh :fail: I just noticed you are the author of that repo @loonpwn 😅

**Comment by loonpwn** [comment]
> oh :fail: I just noticed you are the author of that repo @loonpwn

Haha good to know someone is watching :eyes: 

Update for you @Atinux:

To implement this using the loader [vue-windicss-preprocess](https://github.com/windicss/vue-windicss-preprocess) is pretty much there. The missing pieces are: the loader doesn't support passing the config in as an object (breaking hooks), which I have sent a [PR](https://github.com/windicss/vue-windicss-preprocess/pull/5) for and updating the documentation site.

I am a little bit concerned with this issue https://github.com/windicss/vue-windicss-preprocess/issues/3. If the base loader has some bugs with vendor packages then it may trip up some users. Will need some more testing. 

Code is here: https://github.com/loonpwn/tailwindcss-module/commit/0670b9751ae36c172583cdb62b89b23d5ed96e29

**Comment by viennv1709** [comment]
@Atinux Could you publish the roadmap for Nuxt3? I can't wait to know when it's released

**Comment by Mikaleb** [comment]
@viennv1709 I think we'll get all details after the VueJS Amsterdam talks. You can follow it live next week though, I sure will !

**Comment by alexcroox** [comment]
This may not be required anymore, Adam seems to be working on vastly improving Tailwind HMR/build times in the core of tailwind:

https://twitter.com/adamwathan/status/1366492530569850880

https://twitter.com/adamwathan/status/1366509825186795524

**Comment by loonpwn** [comment]
Windicss implementation will released as a seperate package. This can probably be closed.

**Comment by alexcroox** [comment]
https://blog.tailwindcss.com/just-in-time-the-next-generation-of-tailwind-css
