### ISSUE TITLE
production miss attribute 

### ISSUE THREAD

**Issue by weishax** [nuxt-community/tailwindcss-module#274]
rep: [https://github.com/weishax/purecss](https://github.com/weishax/purecss)
**dev: right**
<img width="1635" alt="截屏2021-03-02 22 29 17" src="https://user-images.githubusercontent.com/40553114/109664750-7144f980-7ba8-11eb-904a-e23332f6361c.png">

**production: miss 'bg-blue-500' and 'flex-1'**
<img width="1419" alt="截屏2021-03-02 22 32 03" src="https://user-images.githubusercontent.com/40553114/109664953-ab160000-7ba8-11eb-9397-121ee56c54ae.png">

**create a file(@/view/one.vue)
// tailwind.config.js**
```
module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [
    'components/**/*.vue',
    'layouts/**/*.vue',
    'view/**/*.vue',
    'pages/**/*.vue',
    'plugins/**/*.js',
    'nuxt.config.js'
  ],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
}
```

why miss attribute?  it's random

**Comment by weishax** [comment]
> Could you try with `**/view/**/*.vue` and see if it works?

i try, but not right

**Comment by marceloamp2** [comment]
The same is happening to me. Is losing the bg-red-500 class in production.
