### ISSUE TITLE
Height of input controls shrinks after upgrade 4.0.0-6 > 4.0.0-7

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt-community/tailwindcss-module#289]
### Version
@nuxtjs/tailwindcss: 4.0.0-7 and 8
nuxt: 2.15.3

### Reproduction Link

https://github.com/JabRef/JabRefOnline
In particular this upgrade commit introduced the problems in `login.vue`: https://github.com/JabRef/JabRefOnline/commit/d3add3ca30ae477c09663b8d0a4ce4134db066d5

### Steps to reproduce
Use a input text control, and upgrade from 4.0.0-6 to 4.0.0-7.

### What is Expected?
Looks the same as before the upgrade, namely
![image](https://user-images.githubusercontent.com/5037600/111010236-3146f900-8396-11eb-9b30-3795833c4e57.png)

### What is actually happening?
Height decreases to 
![image](https://user-images.githubusercontent.com/5037600/111010255-3f951500-8396-11eb-949c-2b883d8b8ef7.png)

**Comment by Atinux** [comment]
Please try again with `4.0.0-12`

**Comment by tobiasdiez** [comment]
Both 4.0.0-12 and 4.0.1 work. Thanks!
