### ISSUE TITLE
Just-in-time compiler support

### ISSUE THREAD

**Issue by acidjazz** [nuxt-community/tailwindcss-module#292]
This was just released:

https://youtu.be/3O_3X7InOw8

It would be nice to have:

- [ ] An example or instruction on how we can extend the PostCSS config to enable this
- [ ] Maybe support this option in the module at some point by detecting development mode?

Here is the [compiler](https://github.com/tailwindlabs/tailwindcss-jit) and here is a [Blog post about it](https://blog.tailwindcss.com/just-in-time-the-next-generation-of-tailwind-css)

PostCSS Example:

```js
  // postcss.config.js
  module.exports = {
    plugins: {
      '@tailwindcss/jit': {},
      autoprefixer: {},
    }
  }
```

**Comment by Atinux** [comment]
See #287 

It will be only a `jit: true` option to activate it.

I already contributed to tailwindjit before the release :)

**Comment by acidjazz** [comment]
![image](https://user-images.githubusercontent.com/967369/111209172-b0f0e580-8599-11eb-9055-f8eefb648b5f.png)

Awesome!!

**Comment by IgnisDa** [comment]
It confused me for some time, but if JIT is not being activated for you (you will get a message in the console saying it is activated) despite the settings above, you'll have to update, ie, `"@nuxtjs/tailwindcss": "^4.0.1",` in `devDependencies` in your `package.json`.
