### ISSUE TITLE
Safelist option doesn't work ?

### ISSUE THREAD

**Issue by joffreyBerrier** [nuxt-community/tailwindcss-module#312]
### Version
@nuxtjs/tailwindcss: ^4.0.1
nuxt: 2.15.3

### Reproduction Link
https://codesandbox.io/s/elegant-tu-xipm4

### Steps to reproduce
- Add classes on `purge: { options: { safelist: [] } }` doesn't work

### What is Expected?
- I would like to force tailwind to keep safelist classes

### What is actually happening?
- Safelist doesn't worked

**Comment by joffreyBerrier** [comment]
@Atinux  you didn't have access to the codesandbox reproduction link ? 
=> https://codesandbox.io/s/elegant-tu-xipm4

**Comment by web2033** [comment]
You're using JIT which doesn't support it yet
https://github.com/tailwindlabs/tailwindcss-jit#known-limitations

**Comment by joffreyBerrier** [comment]
Thx @web2033 but `purge: { content: [] }` it works?

**Comment by web2033** [comment]
I think with JIT it works in reverse. It's not purging now but creating classes on the fly.

**Comment by joffreyBerrier** [comment]
Ok, to solved the problem I have created a fake component with all the classes I want to safe which I called on the content array  and its worked but it's not pretty

**Comment by joffreyBerrier** [comment]
@web2033 "Advanced PurgeCSS options like safelist aren't supported yet since we aren't actually using PurgeCSS. We'll add a way to safelist classes for sure though. For now, a safelist.txt file somewhere in your project with all the classes you want to safelist will work fine."

it works?

**Comment by joffreyBerrier** [comment]
Create a `safelist.txt` which contains all your classes you want to safe:
```txt
// Safelist.txt
md:w-1/2
md:w-6/12
...
```

Call the file on the content section of the purge

```javascript
purge: {
    content: [
      './safelist.txt',
    ],
  },
```

**Comment by joffreyBerrier** [comment]
Create a `safelist.txt` which contains all your classes you want to safe:
```txt
// Safelist.txt
md:w-1/2
md:w-6/12
...
```

Call the file on the content section of the purge

```javascript
purge: {
    content: [
      './safelist.txt',
    ],
  },
```

**Comment by IsidroMar95** [comment]
is there another way to add safelist without add some fake file like `safelist.txt` ?
