### ISSUE TITLE
___CSS_LOADER_URL_REPLACEMENT_0___ issue when jit set to true

### ISSUE THREAD

**Issue by lsbyerley** [nuxt-community/tailwindcss-module#314]
<!-- **IMPORTANT!**
When `jit:true`, a css-loader error pops up on subsequent compiles pointing to the tailwind.css file. On the initial compile, it succeeds, but when making an edit and re-compiling, this error comes up.

```
ERROR  in ./assets/css/tailwind.css

Module build failed (from ./node_modules/css-loader/dist/cjs.js):  
Error: Can't resolve '___CSS_LOADER_URL_REPLACEMENT_0___' in ...
```

tailwind.css file:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

### Version
@nuxtjs/tailwindcss: 4.0.1
nuxt: 2.15.3

### What is Expected?
Should compile fine on subsequent compiles. Posting this issue here in case anyone else runs into it as I can't seem to find anything about it any where.

**Comment by Atinux** [comment]
Please create a reproduction
