### ISSUE TITLE
Can't extend tailwind config by tailwindcss:config hook

### ISSUE THREAD

**Issue by mercs600** [nuxt-community/tailwindcss-module#316]
### Version
Fresh setup by create-nuxt-app with newest tailwind module 
```json
 "dependencies": {
    "nuxt": "^2.15.3"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^4.0.1",
    "postcss": "^8.2.8"
  }
```

### Reproduction Link
https://github.com/mercs600/nuxt-tailwind-config-override

### Steps to reproduce
Please look at the repository where I have simple component and use @apply directive to setup simple margin based on extended setup. 
https://github.com/mercs600/nuxt-tailwind-config-override/blob/master/components/TailwindSetup.vue 
```vue
<style lang="postcss">
p {
  @apply mb;
}
</style>
```

The issue is that nuxt/tailwindcss is not able to read my extended configuration from the module where I defined default spacing - so @apply mb should works. 
https://github.com/mercs600/nuxt-tailwind-config-override/blob/master/modules/tailwindsetup.js
```js
import defu from 'defu'
const extendTailwindConfig = {
  theme: {
    extend: {
      spacing: {
        DEFAULT: '.5rem'
      }
    }
  }
}
const TailwindSetup = function (options) {
  this.nuxt.hook('tailwindcss:config', function (tailwindConfig) {
    tailwindConfig = defu(tailwindConfig, extendTailwindConfig)
    console.log(tailwindConfig)
  })
  console.log(this.nuxt.options.tailwindcss)
}

export default TailwindSetup
```

It works only when I extend config by tailwind.config.js 
https://github.com/mercs600/nuxt-tailwind-config-override/blob/master/_tailwind.config.js  - you can change name of the file
or in the nuxt.config.js
https://github.com/mercs600/nuxt-tailwind-config-override/blob/master/nuxt.config.js#L38  - you have to uncomment config. 

### What is Expected?
I should be able to override/extend nuxt configuration from the nuxt hook module. It worked before

### What is actually happening?
Right now when I extend the configuration from the hook- I can see the results in the console that configuration was overided, but it doesn't work

<img width="940" alt="Zrzut ekranu 2021-03-22 o 13 49 15" src="https://user-images.githubusercontent.com/7935392/111992163-65988300-8b15-11eb-9987-0799014f97b4.png">

The same issue with overriding the purge content array.

**Comment by Atinux** [comment]
Hi @mercs600 

It is tricky since we cannot update the reference of the object, could you try with:

```js
this.nuxt.hook('tailwindcss:config', function (tailwindConfig) {
    Object.assign(tailwindConfig, defu(tailwindConfig, extendTailwindConfig))
    console.log(tailwindConfig)
  })
```

**Comment by mercs600** [comment]
@Atinux right, my bad 😅  thank you for catching that 👍
