### ISSUE TITLE
Upgrading to 4.0.3 results in sass-loader on npm run build

### ISSUE THREAD

**Issue by jhhosbond** [nuxt-community/tailwindcss-module#327]
Trying to upgrade to @nuxtjs/tailwind 4.0.3 as especially the JIT feature is attractive! Howver, I keep getting errors when trying to build (npm run build) the solution. It works perfectly fine when when doing an npm run dev.

Any ideas as to what I'm missing here?

### **Package.json looks like this:**

![image](https://user-images.githubusercontent.com/9704211/114096031-7b9c9680-98be-11eb-8286-c0ce14c43742.png)

### and **nuxt.config.js relevant sections:**
` buildModules: [
    '@nuxtjs/tailwindcss',
     '@nuxt/postcss8'
  ],`

### **The error** looks like this:
![image](https://user-images.githubusercontent.com/9704211/114096476-0a111800-98bf-11eb-8f42-fac4decc2df2.png)

**Any ideas?**

**Comment by rlam3** [comment]
@jhhosbond did you find a workaround?
