### ISSUE TITLE
How do I include a third-party plugin within the purgeCSS whitelist/safelist?

### ISSUE THREAD

**Issue by JoshuaRobertson** [nuxt-community/tailwindcss-module#328]
## Question

In my Nuxt JS project I am using TailwindCSS for the CSS framework and have included the `vue-datetime` plugin. When compiling the static assets and running the project in production the custom CSS for the `vue-datetime` plugin isn't being included in the minified CSS file. I've read through the Github issues but can't replicate the suggestions. Could you provide some guidance please?

**Related issues**

1. https://github.com/nuxt-community/tailwindcss-module/issues/39
2. https://github.com/nuxt-community/tailwindcss-module/issues/55
3. https://github.com/nuxt-community/tailwindcss-module/issues/118
4. https://github.com/nuxt-community/tailwindcss-module/issues/312

## Version
- nuxt: "2.14.12"
- @nuxtjs/tailwindcss: "3.4.2"
- vue-datetime: "^1.0.0-beta.14"

### Current config

**nuxt.config.js**

Here is a reduced example of my current config with the relevant plugins listed. You can see I'm trying to include the `path` to the third-party plugin so that the CSS is retained in production.

```javascript
export default {
  css: [
    '~/assets/scss/tailwind.scss'
  ],
  modules: [
    'nuxt-purgecss'
  ]
  /*
  ** Post CSS config
  */
  postcss: {
    plugins: {
      tailwindcss: path.resolve(__dirname, './tailwind.config.js')
    }
  },
  /*
  ** Purge CSS config
  */
  purgeCSS: {
    mode: 'postcss',
    paths: ['./node_modules/vue-datetime/dist/*.min.css']
  }
}
```

**tailwind.config.js**

Here is my current TailwindCSS config. I've tried using `safelist` and `whitelist`, and attempted to include both the Vue files and CSS that reference the classes. Neither have any impact on the final outputted CSS. Is this `purge` section only used for TailwindCSS specific helper classes and if so should I be including the files/classes I want to retain elsewhere?

```javascript
module.exports = {
  purge: {
    content: [
      './node_modules/vue-datetime/src/*.vue',
      './node_modules/vue-datetime/dist/*.min.css'
    ],
    options: {
      safelist: ['vdatetime-overlay'],
    }
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {
      opacity: ['disabled'],
    }
  },
  plugins: [
    require('@tailwindcss/forms')
  ]
}
```

**Comment by sts-ryan-holton** [comment]
I'm getting the same problem

**Comment by cfab** [comment]
same here !

**Comment by andorfermichael** [comment]
can confirm this issues

**Comment by develth** [comment]
this is a real bottleneck, when coming to deploy a ready page and you can´t put it online because of no docs or examples on how to disable / whitelist this stuf...
