### ISSUE TITLE
TailwindCSS classes not working after upgrading to v4.x

### ISSUE THREAD

**Issue by gyenabubakar** [nuxt-community/tailwindcss-module#329]
I've been wanting to use the new `ring...` classes in Tailwind 2 so I tried upgrading, following the steps at [the official site](https://tailwindcss.nuxtjs.org/setup/).

### Version
@nuxtjs/tailwindcss: ^4.0.3
nuxt: ^2.15.3

### Steps to reproduce
Using Yarn:
1. Create a Nuxt application, with version Nuxt version `^2.12.1`
2. Install `@nuxtjs/tailwindcss`  version `^3.4.2`
3. Set the `tailwind.config.js` file to have:
```
const { colors, screens } = require("tailwindcss/defaultTheme");

module.exports = {
	theme: {
		colors: {
			black: colors.black,
			white: colors.white,
			gray: colors.gray,
			orange: colors.orange,
			yellow: colors.yellow,
			green: colors.green,
			red: colors.red,
		},
		screens: {
			xs: { max: "380px" },
			ss: "381px",
			"2xl": "1536px",
			"3xl": "1600px",
			...screens,
		},
	},
	variants: {
		extend: {
			opacity: ["disabled"],
		},
	},
	plugins: [],
};
```

4. Create `tailwind.css` file in the `./assets/css` directory, with content:
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```
5. In `nuxt.config.js`, set `ssr` to `false`
6. Run `nuxt`, to build application,
7. Now, follow the steps at [the official site](https://tailwindcss.nuxtjs.org/setup/) to upgrade `@nuxtjs/tailwindcss`, and build application again.

### What is Expected?
Everything is supposed to work fine, and I'm supposed to be able to use the new features of TailwindCSS 2.

### What is actually happening?
I get several errors, like:

```
ERROR in ./components/profile/ExposeUploadsContent.vue?vue&type=style&index=0&id=15e4bf6c&scoped=true&lang=css& (./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./components/profile/ExposeUploadsContent.vue?vue&type=style&index=0&id=15e4bf6c&scoped=true&lang=css&)
Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(119:0) C:\Users\MIKE\Projects\waartisan_client\components\profile\ExposeUploadsContent.vue The `ring-orange-500` class does not exist, but `ring-green-500` does. If you're sure that `ring-orange-500` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  117 | }
  118 | ._photo img:active {
> 119 | 	@apply ring-2 ring-orange-500;
      | 	                                                 ^
  120 | }
  121 | </style>
```

**Comment by palexandrite** [comment]
I have the similar issue. Any of classes did not grasp after moving to v4. But I have another JavaScript framework. It is Vue3.
