### ISSUE TITLE
Please update tailwind to 2.1

### ISSUE THREAD

**Issue by yuriti** [nuxt-community/tailwindcss-module#330]
Hello, please update the module, tailwind merged the repository with jit

**Comment by thevuong** [comment]
Has the module been abandoned?

**Comment by okaufmann** [comment]
Don't know, but we use this module already with tailwind 2.1 already in the way Adam stated in the referenced issue ✌️

**Comment by CodeDredd** [comment]
duplicate with #326 , closed by #338
