### ISSUE TITLE
Nuxt generate does not work with Sass 

### ISSUE THREAD

**Issue by mjcadz** [nuxt-community/tailwindcss-module#332]
### Version
@nuxtjs/tailwindcss: 4.0.1
nuxt: v2.15.3

### Steps to reproduce

In a vue component apply some tailwind styles while using sass

```
<style scoped lang="sass">
  @layer components
    .background
      @apply bg-black
</style>
```

### What is Expected?

When `nuxt generate` is run the tailwind style should be applied to the 'background' class in the resulting web page.

### What is actually happening?

When `nuxt generate` is run no style is applied from the sass styles. No errors are displayed either.

If `nuxt dev` is run, the sass style is applied as it should be

If the style is changed to css

```
<style scoped>
  @layer components {
    .background {
      @apply bg-black;
    }
  }
</style>
```
The style is applied when `nuxt generate` is run

css works as intended with `nuxt generate`. sass does not.

**Comment by rlam3** [comment]
@mjcadz did you find a workaround?

**Comment by mjcadz** [comment]
No I just ended up reverting to CSS
