### ISSUE TITLE
css not optimized in production build

### ISSUE THREAD

**Issue by chichengjerry** [nuxt-community/tailwindcss-module#334]
### Version
@nuxtjs/tailwindcss: ^4.0.3
nuxt: ^2.15.4

### Reproduction Link
[Sample Repository](https://github.com/chichengjerry/tailwind-example)

1. Simply create a project using `npx create-nuxt-app` with TypeScript and Tailwind framework.
2. Font style isn't necessary, just for presentation.

### Steps to reproduce
Build the project

### What is Expected?
![Google Fonts applied](https://user-images.githubusercontent.com/4081323/115823859-0e523f00-a442-11eb-89c1-526aad27b171.png)
Title with Google fonts correctly applied in development environment

### What is actually happening?
![Font missing](https://user-images.githubusercontent.com/4081323/115823924-29bd4a00-a442-11eb-8e7c-5d64ec20095a.png)
`@import` rules not working in production environment

![Styles are not optimized](https://user-images.githubusercontent.com/4081323/115824058-55d8cb00-a442-11eb-92ca-485604920f2e.png)
And styles are not optimized and minified (`@import` rules should be moved to the top of style)

### Workaround
Configure `nuxt.config.js` with `extractCSS: true` (is this intended purpose?)

**Comment by chichengjerry** [comment]
> Actually I don't recommend to use `extractCSS` for best performances since the CSS is code-splitted with the pages already.

I’m prefer not using `extractCSS: true` too, though it’s irrelevant to the issue.

**Comment by manuelmeindl** [comment]
Regarding css optimization and minification you are not the only one with troubles. See #361

**Comment by ririen** [comment]
Please see my solution and let me know if it helped: https://github.com/nuxt-community/tailwindcss-module/issues/361#issuecomment-872897501

**And also enable JIT!**
