### ISSUE TITLE
Error: Cannot find module '@tailwindcss/jit'

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-community/tailwindcss-module#341]
### Version
@nuxtjs/tailwindcss: 4.1.1
nuxt: 2.15.4

### Reproduction Link
https://github.com/dargmuesli/trapparty/pull/33/checks?check_run_id=2531788691

### Steps to reproduce
Upgrade to `v4.1.1`, then run Nuxt's `build`.

### What is Expected?
There is no breaking change.

### What is actually happening?
`Error: Cannot find module '@tailwindcss/jit'`

**Comment by dargmuesli** [comment]
See https://github.com/nuxt-community/tailwindcss-module/pull/338#issuecomment-834634795.

To fix this
- change ` ['@nuxtjs/tailwindcss', { jit: true }],` to `'@nuxtjs/tailwindcss',` in `nuxt.config.js`
- add `mode: 'jit',` to `tailwind.config.js`

**Comment by christopher4lis** [comment]
> See [#338 (comment)](https://github.com/nuxt-community/tailwindcss-module/pull/338#issuecomment-834634795).
> 
> To fix this
> 
> * remove `{ jit: true }` from the `buildModules` array in `'@nuxtjs/tailwindcss'` in `nuxt.config.js`
> * add `mode: 'jit'` to `tailwind.config.js`
> 
> The files need to look like this:
> 
> nuxt.config.js
> 
> ```
> export default {
>     buildModules: [
>         '@nuxtjs/tailwindcss'
>     ]
> }
> ```
> 
> tailwind.config.js
> 
> ```
> module.exports = {
>     mode: 'jit'
> }
> ```

Clutch. Thank you for this, confirmed working.

**Comment by christopher4lis** [comment]
Following up here again after a bit of usage—seems that certain classes such as px-0.5 and p-7 aren't working as expected anymore. Know that these were part of a release w/ Tailwind 2, so not sure if the Tailwind version was reverted or something.
