### ISSUE TITLE
Upgrading instructions for v.4.1.x

### ISSUE THREAD

**Issue by acidjazz** [nuxt-community/tailwindcss-module#344]
After upgrading to v4.1.1 I needed to make some config changes after finding https://github.com/nuxt-community/tailwindcss-module/issues/341#issuecomment-834876156

* remove `{ jit: true }` from the `buildModules` array in '@nuxtjs/tailwindcss' in `nuxt.config.js`
* add mode: 'jit' to tailwind.config.js

This issue is just to help put these instructions somewhere when adding it to the docs.

**Comment by Stun3R** [comment]
Related & fix in #342

**Comment by acidjazz** [comment]
thanks @Stun3R , since i see thats closed and the docs are updated ill close this as well
