### ISSUE TITLE
Nested CSS not compiled correctly

### ISSUE THREAD

**Issue by mydnic** [nuxt-community/tailwindcss-module#348]
### Version
@nuxtjs/tailwindcss: ^4.1.2
nuxt: ^2.15.6

### Reproduction Link
https://github.com/mydnic/nuxt-test

### Steps to reproduce
clone this project https://github.com/mydnic/nuxt-test and run `yarn && yarn dev` 

### What is Expected?
The css in /assets/css/components/nav.scss should correctly generate the `.sidebar-nav-item .icon` css rules.
The svg icon should have the right size and color

### What is actually happening?
It looks like only the .sidebar-nav-item class is compiled correctly, but not the .icon class
The svg icon has no size applied so it's super big

----
I've seen my nuxt project design completely broken up after some dependabot automatic version update.
Not sure if it comes from nuxt/tailwindcss-module 4.1.2 version or from a postcss nesting module update ?

**Comment by othy54** [comment]
i have the same problem, my css is broken it's like a problem with postcss

I used to make style like this : 

.services-inactive {
   .menu-list {
    @apply w-10/12 mx-16;
  }

   .services-list {
    @apply w-0 mx-0;
  }
}

but since today it works no more i resolved by adding & like : 

.services-inactive {
  & .menu-list {
    @apply w-10/12 mx-16;
  }

  & .services-list {
    @apply w-0 mx-0;
  }
}

but still weird ...

**Comment by dami2** [comment]
Adding 

`build: {
      postcss: {
        plugins: {
          'postcss-nested': {}                                                                                                                                         
        }
      }
    }`

to nuxt.config.js seems to fix it.

I belive this has to do with the switch to postcss-nesting in [v4.0.1 ](https://github.com/nuxt-community/tailwindcss-module/releases/tag/v4.0.1)
