### ISSUE TITLE
Media queries not being matched on viewport

### ISSUE THREAD

**Issue by dami2** [nuxt-community/tailwindcss-module#351]
### Version
@nuxtjs/tailwindcss: ^4.1.2
nuxt: ^2.15.6

### Reproduction Link

- Gif here: https://www.dropbox.com/s/i69xsydvwdujrun/issue-tailwind.gif?dl=0
- Reproduction link here: https://gm0eg.sse.codesandbox.io
- CodeSandbox here: https://codesandbox.io/s/condescending-frog-gm0eg

Weird enough, if you change to Responsive Mode with Dev Tools, the layout appears as a "minified version of the desktop layout".
But It shows fine if you resize the browser window though

How weird is that?

![issue-tailwind](https://user-images.githubusercontent.com/271794/119019747-e2a87300-b973-11eb-943b-2349062a2b9c.gif)

### Steps to reproduce

1. Go to reproduction link
2. Open Browser's Dev Tools
3. Set Responsive Mode

### What is Expected?

Layout should be styled by Tailwind's media queries. 

### What is actually happening?

Looks like media query is still matching xl break point.

**Comment by roennow** [comment]
Looks like viewport isn't added to your head

**Comment by dami2** [comment]
> Looks like viewport isn't added to your head

Good point there

I've made a little new test, if you add a [head property](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-head) to nuxt.config.js explicity setting a a viewport meta like this:

` head: {
    meta: [
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
    ]
  }`

it works fine.

So this makes viewport meta a mandatory config to the module (should it state in the docs?)
Or at least it worth a build console warning?

**Comment by roennow** [comment]
> So this makes viewport meta a mandatory config to the module (should it state in the docs?)

This is mandatory for responsive designs and not related to neither tailwind nor the module :)

**Comment by dami2** [comment]
> > So this makes viewport meta a mandatory config to the module (should it state in the docs?)
> 
> This is mandatory for responsive designs and not related to neither tailwind nor the module :)

fair enough, closing the issue, regards :wave:
