### ISSUE TITLE
Hot reloading does not work for HTML templates

### ISSUE THREAD

**Issue by lmm-git** [nuxt-community/tailwindcss-module#357]
### Version
@nuxtjs/tailwindcss: 4.1.1
nuxt: 2.15.6

### Reproduction Link
https://rechenknecht.net/lmm/nuxt-tailwind-bug-report

### Steps to reproduce
1. Clone repo
2. Run `yarn dev`
3. Change any text in `pages/index.vue` (e.g. schaukasten -> schaukasten2)

### What is Expected?
1. Hot reloading should work

### What is actually happening?
* Text is not updated until page in browser is manually refreshed
* A loading indicator is shown in the bottom right corner (file change is detected)

### Notes
* Hot reloading works for removing components in the template (e.g. removing or adding the `Logo` component)
* Hot reloading works for scripts
* Hot reloading works for styles
* Works with other UI frameworks like vuetify

**Comment by cpt-n3mo** [comment]
Having the same issue..
on clean create-nuxt-app with tailwind.
but also stops the vuetify classes from hot reloading when tailwind is installed along side of it a with prefix.

using:
"nuxt": "^2.15.3",
"@nuxtjs/tailwindcss": "^4.0.1",

**Comment by cpt-n3mo** [comment]
Any progress on this bug..? Or maybe a workaround.. ?

**Comment by cpt-n3mo** [comment]
Good day..

I have been playing around with it for a bit, and i noticed that it keeps working fine when there is no other css defined within `<style></style>`, once you add anything to it id,class,etc it stops the hot reload from working, removing it again needs a manual refresh to allow the hot reload to start working again,
inline styles seem to work fine as well,

this also only seems to happen when the styles are defined within that component or page, as when defining a scoped style in `layout/default.vue`  this does not effect the hot reload of let say the `pages/index.vue` 

so a kind of bad workaround would be, to not define any styles within the style tags, and put everything inline..

i hope this gets fixed soon, as this kind of sucks.. 
i would help my self but i would not know were to start.. 

kind regards.

**Comment by cpt-n3mo** [comment]
Good day again..

I have been playing around some more and have a little update, that when there is something commented out withing the style tags, as in if there is any form of type inside the style tags, hot reload stops working,... i have been looking into hot-update.js but i cant make heads or tails of it..  as it seems the updates are being pushed through. as the hot-update does show the modification,.. its just seems to not updating the DOM accordingly..

also removing tailwind from build modules does not solve the problem, only removing postcss with removal of node_modules and package-lock.json, will fix the problem.
so i suspect that postcss is interfering with webpack somehow. as even when tailwindcss in not active in nuxt.config.js hot reload still is not working..

**Comment by paplco** [comment]
> this fixed the problem for me.. cheers!!!

downgrading as specified fixed issue for me also

**Comment by IgnisDa** [comment]
I managed to take a screenshot. This message briefly appears in the console before the whole page is force reloaded.

![tailwindcss](https://user-images.githubusercontent.com/60938164/123501489-f5912000-d662-11eb-9d6d-1b33266edf63.png)

**Comment by fabis94** [comment]
I'm having the same issue
![image](https://user-images.githubusercontent.com/938316/124479367-ddca4200-ddae-11eb-983a-7fa5f20b18ce.png)

**Comment by atlesque** [comment]
> > this fixed the problem for me.. cheers!!!
> 
> downgrading as specified fixed issue for me also

The workaround works but it downgrades Tailwind to v1.9.x which disables other handy features of Tailwind 2.x like arbitrary values. So it would be great if we could find a better solution which works with the latest included Tailwind version 2.x.

**Comment by ewilan-riviere** [comment]
I've a template with nuxt app and tailwind 2.0 with JIT without bug, I didn't find the difference with new nuxt app, but this works: [https://gitlab.com/ewilan-riviere/nuxt-tailwind-template](https://gitlab.com/ewilan-riviere/nuxt-tailwind-template)

**Comment by productfrontenddeveloper** [comment]
some problem and 4.1.0 4.2.1 Compilation speed is 2x slow compared to

**Comment by productfrontenddeveloper** [comment]
@Atinux -> https://github.com/tailwindlabs/tailwindcss/issues/4940#issuecomment-877809243

**Comment by HenrijsS** [comment]
Downgrading to `tailwindcss: 2.1.0` fixes the problem for me.

**Comment by fabis94** [comment]
@HenrijsS Didn't seem to fix it for me.

![image](https://user-images.githubusercontent.com/938316/126116947-60922aea-fe8a-42ec-82f9-142f57c7dbc4.png)

Tailwind 2.1.0 and JIT turned on.

**Comment by cpt-n3mo** [comment]
What version of nuxt are you using..?
Also to the dev's.. what's up why this bug still existing... is there some
update on progress fixing this bug, next to downgrading .... are you only
planning to fix this in nuxt3 release ..?

Regards

**Comment by fabis94** [comment]
@cpt-n3mo I'm on nuxt 2.15.7, if you were asking me

**Comment by cpt-n3mo** [comment]
Sorry indeed I was talking to you 😅

Did you remove package lock and node module folder..? Then a fresh npm
install..? Regards..

**Comment by fabis94** [comment]
@cpt-n3mo Yes, I did do that, didn't seem to make a difference.

tailwindcss@2.1.0
@nuxtjs/tailwindcss@4.2.1 
nuxt@2.15.7

**Comment by HenrijsS** [comment]
@fabis94 
Can you paste your CSS file here? The tailwind one in assets.

**Comment by fabis94** [comment]
@HenrijsS It's the default tailwind css:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Tailwind config:
```js
/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */

module.exports = {
  mode: 'jit',
  presets: [require('@fabis/custom-tailwind-theme').TailwindPreset],
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'src/**/*.{vue,js,ts}',
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'node_modules/**/*.vue',
    ],
  },
};
```

Here's the plugin inside the custom tailwind theme:
```js
const plugin = require('tailwindcss/plugin');

/**
 * This theme adds all of the custom styling that can't be done through the preset alone
 */
module.exports = plugin(function ({
  addBase,
  addComponents,
  addUtilities,
  theme,
}) {
  const screens = theme('screens', {});

  // BASE LAYER
  addBase({
    // Responsive font classes depending on locale
    '.font-sans': {
      'font-family': "'SomeFont', sans-serif",
    },
    "html[lang='ja'] .font-sans": {
      'font-family': "'SomeFontJP', sans-serif",
    },
  });

  // Base font applied on body
  addBase({
    body: {
      '@apply font-sans': {},
    },
  });

  // COMPONENTS LAYER
  const headingCount = 5;
  const headingDefinitions = {};
  for (let i = 1; i <= headingCount; i++) {
    headingDefinitions[`.heading-${i}`] = {
      [`@apply text-h${i} font-bold`]: {},
    };
  }

  addComponents(
    {
      // Heading classes
      ...headingDefinitions,
      // Links
      '.link-undecorated': {
        '@apply text-blue-700 cursor-pointer': {},
      },
      '.link': {
        '@apply link-undecorated hover:underline': {},
      },
    },
    { variants: ['responsive'] }
  );

  // UTILITIES LAYER
  // Making font-size/line-height dynamic for some text utility classes
  const smSize = screens['sm'];
  addUtilities({
    [`@media (min-width: ${smSize})`]: {
      '.text-h1': {
        'font-size': '48px',
        'line-height': '60px',
      },
      '.text-h2': {
        'font-size': '36px',
        'line-height': '46px',
      },
    },
  });
});

```

**Comment by HenrijsS** [comment]
@fabis94 Did you try the good old disable-enable debugging?
Remove the plugin and the theme. Check if it compiles. If yes - turn on one-by-one and see which part causes the bug.
If it still throws the error with vanilla Tailwind and default config, then I have no clue.

**Comment by fabis94** [comment]
@HenrijsS Thanks for the effort, but that didn't help either. I removed the plugin, even turned off JIT, but the issue persists

**Comment by HenrijsS** [comment]
@fabis94  Expand the error and look for the stack trace and look which line is the Unaccepted module.

**Comment by fabis94** [comment]
@HenrijsS It's the same issue as before, it says that tailwind.css can't be reloaded:

![image](https://user-images.githubusercontent.com/938316/126604225-d7eaf807-6c07-4147-97dd-3cae334cfd92.png)

**Comment by HenrijsS** [comment]
@fabis94 
![C41F8E64-D4FD-4AF4-BF86-EED80D458CE7](https://user-images.githubusercontent.com/49265222/126604318-d50b844e-adb1-487e-a09e-2545eeea7111.png)

Click the arrows to expand the error. You should see on which lines the error occurs.

**Comment by fabis94** [comment]
@HenrijsS Any specific line/file I should be checking? The files in the stack trace just link to the webpack-hot-middleware internals which I don't really know anything about. Doesn't seem like there's anything useful here (at least to me not having any experience with the internals of webpack-hot-middleware).

![image](https://user-images.githubusercontent.com/938316/126604551-68a6b72c-0333-4dfa-bf64-401906e0cd32.png)

**Comment by HenrijsS** [comment]
@fabis94 I literally have the same config and package versions on my project and I don't see these issues.
And yeah, the errors don't show much.
Can you paste your nuxt.config.js ?

**Comment by fabis94** [comment]
@HenrijsS Ok I debugged this some more and it looks like with JIT turned off the full page reload and warning only appear on the first change. Subsequent changes to the Vue file correctly hot reload without causing a full reload, which will be good enough, I suppose.

With JIT turned on, however, it causes a full page reload every time so there's still some sort of issue there.

Regarding my nuxt config, here it is:

```typescript
import LodashModuleReplacementPlugin from 'lodash-webpack-plugin';
import { NuxtConfig } from '@nuxt/types';

const config: NuxtConfig = {
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'XXXX',
    htmlAttrs: {
      lang: 'en',
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: ['@fabis/custom-tailwind-theme/stylesheets/font-sans.css'],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    {
      src: '~/src/core/_/auth/plugins/clientAuthValidityCheckPlugin.ts',
      mode: 'client',
    },
  ],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    // https://go.nuxtjs.dev/stylelint
    '@nuxtjs/stylelint-module',
    // https://go.nuxtjs.dev/tailwindcss
    '@nuxtjs/tailwindcss',
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {},

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    extractCSS: true,

    extend(config, { isClient }) {
      // Init & preparation
      if (!config.plugins) {
        config.plugins = [];
      }

      if (!config.resolve?.alias) {
        config.resolve = config.resolve || {};
        config.resolve.alias = {};
      }

      if (!config.externals) {
        config.externals = {};
      }
      const externals = config.externals as Record<string, string>; // TypeScript types are too strict here

      // Externalizing deps from client builds (when deps are only necessary on the server)
      if (isClient) {
        externals.https = 'undefined';
      }

      // This will optimize the size of lodash
      // NOTE: This plugin will cause Lodash to act differently than you would expect! Read more: https://github.com/lodash/lodash-webpack-plugin
      config.plugins.push(new LodashModuleReplacementPlugin());
    },

    babel: {
      presets({ envName }) {
        if (envName === 'modern') {
          throw new Error('Modern build not supported currently');
        }

        const envTargets = {
          client: { browsers: ['last 2 versions and since 2018'] },
          server: { node: 'current' },
        };
        return [
          [
            '@nuxt/babel-preset-app',
            {
              corejs: { version: '3.15.2' },
              useBuiltIns: 'entry',
              targets: envTargets[envName],
            },
          ],
        ];
      },
      plugins: [
        'lodash', // Decreases build size
      ],
    },
  },
  server: {
    port: 3500,
    host: '0.0.0.0',
  },

  render: {
    bundleRenderer: {
      runInNewContext: false, // Fixes Inversify in dev builds https://github.com/nuxt/nuxt.js/issues/6076
    },
  },
};

export default config;

```

**Comment by HenrijsS** [comment]
@fabis94 Where did you import the tailwind.css file? 
Mine is imported in the global CSS object:
```
	// Global CSS: https://go.nuxtjs.dev/config-css
	css: [
		'@/assets/stylesheet.css',
		'vue-multiselect/dist/vue-multiselect.min.css',
		'swiper/css/swiper.css',
		'photoswipe/dist/photoswipe.css',
		'photoswipe/dist/default-skin/default-skin.css',
		'@/assets/tailwind.css',
	],
	```

**Comment by HenrijsS** [comment]
@fabis94 Okay. The deletion of tailwind.css did nothing for me.
I'm out of luck. Maybe someone with a fresh eye can look into this.

**Comment by cpt-n3mo** [comment]
> 
> 
> @cpt-n3mo Yes, I did do that, didn't seem to make a difference.
> 
> tailwindcss@2.1.0
> @nuxtjs/tailwindcss@4.2.1
> nuxt@2.15.7

i see, remove the taiwindcss@2.1.0 and @nuxtjs/tailwindcss@4.2.1 and to dev deps  "@nuxtjs/tailwindcss": "~3.4.3", "postcss": "~7.0.36" be sure to use these versions with a tilda "~" . 
then it should work you need these versions, specificly, add the postcss as well, newer versions dont work for the older nuxtjs/tailwindcss 4.2.1 package.

remove package lock and node modules folder and do a npm install or yarn what ever you use..

it should work this way. regards.

**Comment by fabis94** [comment]
@cpt-n3mo Does this mean also downgrading PostCSS to 7.x? Cause I need Nuxt to use PostCSS 8 and Tailwind 2+

**Comment by cpt-n3mo** [comment]
indeed that is the case .. its deff not ideal but it the only combination i found that works..
regards.

**Comment by atlesque** [comment]
Here's an easy way to reproduce the issue:

1. Run `npx create-nuxt-app` and generate a new Nuxt project
2. Run `npx tailwindcss init` to create a Tailwind config file
3. Edit `tailwind.config.js` and add `mode: 'JIT',` to enable the JIT compiler
4. Start the dev server using `npm run dev`
5. Open Chrome and open the Dev Tools
5. Enable `Preserve log` in the Dev Tools' console
6. Edit `/components/Tutorial.vue` and add an arbitrary value to an element, e.g. `bg-[#ee3456]`
7. The error (as previously posted) is shown: `[HMR] The following modules couldn't be hot updated: (Full reload needed)`

Expected: To see the changes without page reload, using HMR.

The issue appears to be related to how Tailwind JIT "caches" the previously used classes. Continuing from the previous steps:

1. Change arbitrary value from `bg-[#ee3456]` to something else, e.g. `bg-[#ee3457]`
2. HMR breaks and full reload happens
3. Now change the value back to a value which you have used before, e.g. `bg-[#ee3456]`
4. HMR works fine

The moment you add a class, whether built-in or arbitrary, which Tailwind (or the CSS loader?) has never seen before, it will cause HMR to break. Once the class has been cached somehow, HMR will work okay.

**Comment by NotHolst** [comment]
Any news on this. is it being worked on ?

**Comment by WebDevPJ** [comment]
Keeping this alive, any updates on this?

**Comment by HenrijsS** [comment]
I think all module development is on hold in preparation for Nuxt 3, so don't expect any updates.
Issues are only piling on without any updates.

**Comment by costpawa** [comment]
> UPDATE!.. WORKAROUND!
> edit package.json whith the following versions,
> ` "devDependencies": { "@nuxtjs/tailwindcss": "~3.4.3", "postcss": "~7.0.36" }`
> `rm -rf node_modules package-lock.json `
> `npm install`
> 
> this fixed the problem for me.. cheers!!!

it's working, thanks!

**Comment by areindl** [comment]
Is there any solution that does **not** involve downgrading to PostCSS v7?

**Comment by productfrontenddeveloper** [comment]
> Is there any solution that does **not** involve downgrading to PostCSS v7?

In the above message, it contains all the instructions and even has an example installation.

**Comment by areindl** [comment]
> In the above message, it contains all the instructions and even has an example installation.

Thank you @productfrontenddeveloper but this is - again - a PostCSS 7 solution.

Look at the package.json in the the example:

`"tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.4"`

 I cannot downgrade our application.

**Comment by productfrontenddeveloper** [comment]
> > In the above message, it contains all the instructions and even has an example installation.
> 
> Thank you @productfrontenddeveloper but this is - again - a PostCSS 7 solution.
> 
> Look at the package.json in the the example:
> 
> `"tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.4"`
> 
> I cannot downgrade our application.

There is no other solution at the moment, if you are not using anything related to postcss 8 you have to do this.
As a result, you can use all the features and latest version of tailwindcss. and fixed hot reloading

**Comment by rizkiaprita** [comment]
TL:DR, nuxt doesnt work when youre using tailwind.
solution: back to vue X_X

**Comment by lihbr** [comment]
I managed to pinpoint the issue, for more details see: https://github.com/nuxt/postcss8/issues/24

Temporary Fix

You're likely experiencing this issue if you're:
- On Nuxt `2.15.4` or later;
- Using PostCSS 8 (if you're using `@nuxtjs/tailwindcss 4`, your are).

Disabling `icss` compile type in your build options should fix the issue (but might introduce others if you're relying on SASS, see: https://github.com/nuxt/nuxt.js/pull/9014):
```javascript
// nuxt.config.js
export default {
	/* ... */

	build: {
		loaders: {
			css: {
				modules: false,
			},
		},
	}
}
```

Cheers!

**Comment by the94air** [comment]
commenting the `./nuxt.config.{js,ts}',` line seemed to fix it 😃
https://github.com/nuxt-community/tailwindcss-module/issues/406#issuecomment-998760314

**Comment by oezkancodes** [comment]
I solved it by removing the `@nuxtjs/style-resources` [module](https://github.com/nuxt-community/style-resources-module). I didn't know I still had it while not using it. HMR works now.

**Comment by creazy231** [comment]
Still facing the same problem using mentioned workarounds the be able to use TailwindCSS v3

**Comment by lihbr** [comment]
> Still facing the same problem using mentioned workarounds the be able to use TailwindCSS v3

TailwindCSS 3 might be a whole new issue of its own yeah ^^'

**Comment by vedmant** [comment]
Any updated on this with latest v5 version and Tailwind 3? I still have this issue, HMR is not working if previously not used Tailwind class is added to template.

**Comment by modex98** [comment]
i don't think it's practical for most people, the bundles are too heavy
any Please what is the right combination ? (versions) to make this work

**Comment by ahmetonurslmz** [comment]
Hello,

I encounter the issue and fixed this way. You can look and try to fix for your problem.

[https://en.ahmetonursolmaz.com.tr/nuxt-hot-reload-isnt-working/](https://en.ahmetonursolmaz.com.tr/nuxt-hot-reload-isnt-working/)

**Comment by worldzhao** [comment]
> Any updated on this with latest v5 version and Tailwind 3? I still have this issue, HMR is not working if previously not used Tailwind class is added to template, it reloads whole page:
> 
> ```
> [HMR] The following modules couldn't be hot updated: (Full reload needed)
> This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves.
> [HMR]  - ./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--3-oneOf-1-2!./assets/css/tailwind.css
> ```

any solution for this?  @nuxtjs/tailwindcss@6.7.0,nuxt@2.17.0 still has this problem
