### ISSUE TITLE
Upgrading Tailwindcss version

### ISSUE THREAD

**Issue by Phojie** [nuxt-community/tailwindcss-module#364]

**Comment by gustojs** [comment]
By removing the module and adding it again, you'll have Tailwind 2.2 installed.

But for me, it broke JIT. That may be due to some other issue though.

**Comment by yshrsmz** [comment]
or just refreshing a lockfile should work.

tailwindcss v2.2 updated postcss-purgecss to v4, which dropped the support for postcss v7. I'm wondering if this causes some issue, as many of the nuxt's dependency still uses postcss v7.

**Comment by aliwesome** [comment]
That's just what we really need.

**Comment by existe-deja** [comment]
Just a line on the doc on how to manually update tailwind to the latest version would be nice.

**Comment by aliwesome** [comment]
Same request flows here too. https://github.com/nuxt-community/tailwindcss-module/issues/406
