### ISSUE TITLE
New peer feature from tailwind version 2.2

### ISSUE THREAD

**Issue by l10rdev** [nuxt-community/tailwindcss-module#372]
Hi i wanted to use the latest features  (peer selector) from tailwind 2.2. As i saw nuxt/tailwind uses 2.1 is there any updated expected shortly or is there an alternative way?

**Comment by productfrontenddeveloper** [comment]
`yarn upgrade @nuxtjs/tailwindcss`

**Comment by productfrontenddeveloper** [comment]
and used  2.2 

https://github.com/nuxt-community/tailwindcss-module/blob/486e3dfcd90405e7dade38b233ef04ccca08a645/yarn.lock#L11717-L11720

**Comment by l10rdev** [comment]
Thank you. Whats also imporant is to enable jit mode in tailwindcofnig as peer-* is only working in jit mode:
https://blog.tailwindcss.com/tailwindcss-2-2
https://tailwindcss.com/docs/just-in-time-mode
