### ISSUE TITLE
Autoprefixer and Tailwind 2

### ISSUE THREAD

**Issue by LeCoupa** [nuxt-community/tailwindcss-module#379]
Hello :-), I don't really know why but it seems like prefixes are not added automatically when I build the app with `npm run build`.

For instance, no prefixes are added for `appearance-none` which causes issues on iOS Safari.

```css
.appearance-none {
    appearance: none!important;
}
```

I have followed all instructions [on the Nuxt/TailwindCSS Setup Guide](https://tailwindcss.nuxtjs.org/setup) and I am also using JIT.

If someone has an idea of what is happening. I can't figure it out. It seemed to me that autoprefixer was working directly with Nuxt without anything to configure other than installing `autoprefixer` as a dev dependency. :)

**Comment by hmaesta** [comment]
Did you installed `autoprefixer` and added to `tailwind.config.js`?

```js
const config = {
	mode: "jit",
	plugins: [
		require('autoprefixer'),
// (...)
```

**Comment by CodingWithNuke** [comment]
Autoprefixer doesn't seem to be working for me either.
