### ISSUE TITLE
Custom color classes not being loaded in view and @apply directives

### ISSUE THREAD

**Issue by Myestery** [nuxt-community/tailwindcss-module#384]
## Question
I run a nuxtjs setup with @nuxtjs/tailwindcss. I've tried to add custom colors 
In my tailwind.config.js
```
module.exports = {
  mode: 'jit',
  theme: {
    colors: {
      'blue-hover': '#6133BD',
      "spaceblack":"var(--color-space-black)"
    },
  },
};
```
In @/assets/css/tailwind.css
```
:root {
    --space-black: #191B24;
}
@tailwind base;
@tailwind components;
@tailwind utilities;

```
When I try to apply the classes in vue, my visual studio code suggests the classes and their styles
```
.bg-spaceblack {
    background-color: var(--color-space-black);
}
.bg-blue-hover {
    --tw-bg-opacity: 1;
    background-color: rgba(97, 51, 189, var(--tw-bg-opacity));
}
```
But when I add them to elements, they don't receive the style, and if I use apply, I get an error 
```
The `bg-spaceblack` class does not exist. If you're sure that `bg-spaceblack` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can 
only be used for classes in the same CSS tree.
```
I've read the documentation and tried everything I've seen online but it doesn't seem to work.
Pls Help!! &#x1F622;

**Comment by Myestery** [comment]
[Link to sandbox](https://codesandbox.io/s/gallant-williamson-dmcbi)
the blue-hover class from nuxt.config.js > tailwind > theme > colors didn't get the custom class of bg

**Comment by hacknug** [comment]
> [Link to sandbox](https://codesandbox.io/s/gallant-williamson-dmcbi) the blue-hover class from nuxt.config.js > tailwind > theme > colors didn't get the custom class of bg

There were a couple of issues in your sandbox that I've addressed here: https://codesandbox.io/s/laughing-butterfly-whl0b?file=/nuxt.config.js:301-315

1. Your theme should go inside the `config` property: https://tailwindcss.nuxtjs.org/options#config
2. Your custom `colors` should be inside of `extend` if you expect to be able to apply Tailwind's default styles
- Make sure to provide the paths where the JIT engine should look for classes https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode (not an issue on your sandbox but it may be on your project)

**Comment by Myestery** [comment]
> > [Link to sandbox](https://codesandbox.io/s/gallant-williamson-dmcbi) the blue-hover class from nuxt.config.js > tailwind > theme > colors didn't get the custom class of bg
> 
> There were a couple of issues in your sandbox that I've addressed here: https://codesandbox.io/s/laughing-butterfly-whl0b?file=/nuxt.config.js:301-315
> 
> 1. Your theme should go inside the `config` property: https://tailwindcss.nuxtjs.org/options#config
> 2. Your custom `colors` should be inside of `extend` if you expect to be able to apply Tailwind's default styles
> 
> * Make sure to provide the paths where the JIT engine should look for classes https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode (not an issue on your sandbox but it may be on your project)

Thanks for your help
