### ISSUE TITLE
Nuxt 3 issue "Cannot read property 'resolveAlias' of undefined"

### ISSUE THREAD

**Issue by nurdism** [nuxt-community/tailwindcss-module#387]
### Version
@nuxtjs/tailwindcss: 4.2.1
nuxt: nuxt3@3.0.0-27234271.da7ff44

### Reproduction Link
https://codesandbox.io/s/hungry-diffie-k8odx

### Steps to reproduce
none

### What is Expected?
no error to be produced

### What is actually happening?
error is produced:
```
ERROR  Cannot restart nuxt:  Cannot read property 'resolveAlias' of undefined
  at Object.tailwindCSSModule (node_modules/@nuxtjs/tailwindcss/dist/index.js:51:36)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:1196:17)
  at initNuxt (node_modules/nuxt3/dist/index.mjs:817:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6762:9)
  ```

**Comment by visini** [comment]
See also #386

**Comment by ChangJoo-Park** [comment]
@nuxt-bridge is same.

**Comment by DengSihan** [comment]
An example of nuxt3 with tailwind: [nuxt3-tailwind](https://github.com/JDIZM/nuxt3-tailwind)

Thanks a lot to [@JDIZM](https://github.com/JDIZM)

**Comment by dacoto97** [comment]
I think this package is no longer needed, because nuxt now uses webpack 5 and already supports tailwindcss.
Install tailwind as next.js:
1. Install Tailwind via npm `npm install -D tailwindcss@latest postcss@latest autoprefixer@latest`
2. Create your configuration file: `npx tailwindcss init -p`
3. Configure Tailwind to remove unused styles in production
```
// tailwind.config.js
module.exports = {
  mode: "jit",
  purge: [
    './components/**/*.{vue,js}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}

```
4. Include Tailwind in your CSS
```
/* ./assets/css/tailwind.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by andysay** [comment]
/* ./assets/css/tailwind.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

not import files on server include domain , works only on localhosst.

**Comment by chrispreisler** [comment]
After upgrading to the latest nuxt3 version, tailwind doesn't work for me anymore. I follow the instructions and yesterday it was working as expected. Haven't change anyhting, but today it doesn't work, without changing anything. It also doesn't show any erros.

**Comment by productfrontenddeveloper** [comment]
@neilmispelaar. @MrParano1d update fixed jit. 
https://github.com/productfrontenddeveloper/nuxt3-app

**Comment by productfrontenddeveloper** [comment]
> @neilmispelaar. @MrParano1d update fixed jit.
> 
> Working nuxt3 with https://github.com/productfrontenddeveloper/nuxt3-app ✅✅✅✅

fixed jit `jit:true` change  -> `mode: 'jit'`

**Comment by imnhasan** [comment]
> An example of nuxt3 with tailwind: [nuxt3-tailwind](https://github.com/JDIZM/nuxt3-tailwind)
> 
> Thanks a lot to [@JDIZM](https://github.com/JDIZM)

yes, this the solution I found

**Comment by imnhasan** [comment]
> > For me worked really simple with following Tailwind CSS Docs and @neilmispelaar recommendation.
> > ```shell
> > # Generate a new nuxt3 app
> > npx nuxi init nuxt3-app
> > 
> > # go into directory
> > cd nuxt3-app
> > 
> > # install dependencies
> > npm install
> > 
> > # install Tailwind necessary dependencies
> > npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
> > 
> > # generate Tailwind and Postcss config
> > npx tailwindcss init -p
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **nuxt.config.ts**
> > ```ts
> > import { defineNuxtConfig } from 'nuxt3'
> > 
> > export default defineNuxtConfig({
> >   // Add entry css file
> >   css: ['tailwindcss/tailwind.css'],
> >   build: {
> >     postcss: {
> >       // add Postcss options
> >       postcssOptions: require('./postcss.config.js'),
> >     },
> >   },
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * You will need to update Tailwind config to purge needed files. Can be copied from [Tailwind Module](https://github.com/nuxt-community/tailwindcss-module/blob/55bdd8dbe407378517f4348d342c7e516ec92aa9/src/tailwind.config.ts#L12-L18)
> 
> This worked amazingly.
> 
> Had to change `css: ['tailwindcss/tailwind.css'],` to `css: ['@/assets/css/tailwind.css']` for better flexibility over my tailwind.css.
> 
> Expecting an update to the tailwind docs around this.

I think this one very simple & nice solution 👍

**Comment by hacknug** [comment]
> @productdevbook Good point.
> 
> In my case `tailwindcss/tailwind.css` never changes. Only `tailwind.config.js` and `postcss.config.js` can be changed. And we can achieve a kind of Server HMR by adding `watch` to config. Use `app.vue` only when have your custom CSS file like `assets/css/tailwind.css`
> 
> **nux.config.ts**
> 
> ```ts
> import { defineNuxtConfig } from 'nuxt3'
> 
> export default defineNuxtConfig({
>   css: ['tailwindcss/tailwind.css'],
>   // Restart server when these change
>   watch: ['~/postcss.config.js', '~/tailwind.config.js'],
>   build: {
>     postcss: {
>       postcssOptions: require('./postcss.config.js'),
>     },
>   },
> })
> ```

`watch` option isn't working for me. Anyone managed to use it to trigger a rebuild+refresh? Don't really care if it does HMR or not in this case.

**Comment by IzakJackson** [comment]
> ```ts
> watch: ['~/postcss.config.js', '~/tailwind.config.js'],
> ```

Trying to figure this out but no luck! Has anyone managed to get it to reload?

**Comment by pi0** [comment]
5.0.0-alpha released with Nuxt 3 and Tailwindcss 3 support. Release notes https://github.com/nuxt-community/tailwindcss-module/releases/tag/v5.0.0-0.
