### ISSUE TITLE
Nuxt-Bridge ' [worker] Invalid or unexpected token '

### ISSUE THREAD

**Issue by ralph993** [nuxt-community/tailwindcss-module#390]
I'm trying to use bridge in my nuxt app, but this error its showing after build, if I remove '@nuxtjs/tailwindcss' from  buildModules the error goes away. Any idea ?

Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
async link (internal/modules/esm/module_job.js:67:21)

**Comment by tobiasdiez** [comment]
This comes from the config viewer. It should work if you temporarily disable it by 
```
  tailwindcss: {
    viewer: false,
  },
```
in your nuxt config.

**Comment by tobiasdiez** [comment]
The problem still persists, and hopefully will be fixed as part of https://github.com/nuxt-community/tailwindcss-module/pull/407
