### ISSUE TITLE
CSS in markdown is purged

### ISSUE THREAD

**Issue by StefanoTesla** [nuxt-community/tailwindcss-module#393]
I double the report cause I don't understant whoes the fault is.

Version:
@nuxt/content: v1.41.0
nuxt: v2.15.3
@nuxtjs/tailwindcss: v4.2.1

### Reproduction Link
https://github.com/StefanoTesla/cssproblem

### Steps to reproduce
generate the repository, and run npn start, div style is broken (the class are purged olso if in safelist)

### What is Expected?
If you made a npm run dev style is ok

### What is actually happening?
generate the repository, and run npn start, div style is broken

# Strange fact

- Copy the div  insiede the two markdown filse and paste in a new, or existing, nuxt page .vue 
- generate the project
- npm start
- style is ok

any suggestions?

**Comment by Atinux** [comment]
You may want to take a look at https://tailwindcss.nuxtjs.org/options#config
