### ISSUE TITLE
How to use variable with @apply?

### ISSUE THREAD

**Issue by AugustBurnsRed** [nuxt-community/tailwindcss-module#409]
Hi, I would like to use variables in <style> using @apply but it's not working.

`<style lang="postcss" scoped>
picture >>> img {
  @apply var(--bg-color);
}
</style>`

`<nuxt-picture
    :style="cssVars"
  />`

`cssVars() {
      return {
        '--bg-color': this.bgColor,
      }
    },`

`bgColor: {
      type: String,
      default: 'bg-blue-500',
    },`

I get the error: The `var(--bg-color)` class does not exist.

It's working if i change the value of the variable to 'blue' and use instead: background-color: var(--bg-color); 

So it's fine if i only use postcss, but it seems that tailwind is running before postcss so it does not read the good variable name. How could i fix that?

thanks!

**Comment by ManasMadrecha** [comment]
You need to use arbitrary notations to use CSS custom properties with Tailwind's `@apply` feature.

E.g., 

```html
<style lang="scss">
details {
    --spacing: 1rem;
    @apply tw-border;
}
details[open] {
    @apply tw-px-[var(--spacing)];
    summary {
      @apply tw-mb-[var(--spacing)] tw-mx-[calc(var(--spacing)_*_-1)];
    }
  }
</style>
```

For CSS custom properties that denote color, you need to add CSS data type as well, e.g., `tw-text-[color:var(--my-var)]`

**Comment by AugustBurnsRed** [comment]
Thanks but i don't think thats going to work for my use case. I need to pass full class name. Not just the color name.

I use Nuxt Image and there is no way to pass class as props. In his parent component like Banner, i could use >>> in style to write the css but i would prefer to do it inline by passing them as props like `<Img :custom_class="'bg-blue-500 text-red-500'" />`

After in my Img component, i have the nuxt-picture and would do something like

```
<nuxt-picture
    :src="src"
    :style="cssVars"
  />

props: {
    customClass: {
      type: String,
      default: '',
    },
    src: {
      type: String,
      default: '/',
    },
  },

cssVars() {
   return {
      '--custom-class': this.customClass,
   }
},

picture >>> img {
  @apply var(--custom-class);
}
```

**Comment by ManasMadrecha** [comment]
### One 

In the last line of your code, try this: 

```
@apply [var(--custom-class)];
```

**Comment by AugustBurnsRed** [comment]
I get: The `[var(--custom-class)]` class does not exist.
