### ISSUE TITLE
tailwind class content does not render in nested Lerna packages 

### ISSUE THREAD

**Issue by davodaslanifakor** [nuxt-community/tailwindcss-module#413]
Hey, I need some help to improve my design-system project.
so I added Lerna for management multi-app in nuxt also use @nuxtjs/tailwindcss.
in Lerna config and nuxt config everything is ok but when use tailwind CSS for my component design class content doesn't know tailwind 
although tailwind  CSS works fine.

```"@nuxtjs/tailwindcss": "^4.2.1"```
see my directory

![image](https://user-images.githubusercontent.com/14367811/148964496-0141b608-9abd-4804-a2c0-f9b1bb273c07.png)

see my loaded component 

![image](https://user-images.githubusercontent.com/14367811/148964741-a95247b6-d6d5-4180-aafb-e965f8970e22.png)

and the result

![image](https://user-images.githubusercontent.com/14367811/148964888-d4933aad-27ee-4b4b-bc8b-3d09c00ea247.png)

in the last image, you can see doesn't load class tailwind.

thank you for your time.

**Comment by mahdi-morovati** [comment]
have you got a solution on it yet?
@davodaslanifakor

**Comment by davodaslanifakor** [comment]
@mahdi-morovati not yet maybe should wait for @Atinux or @pi0

**Comment by soroushJuly** [comment]
I've the same problem. Tailwind classes won't work in my external components which I've imported to my project folders.

**Comment by ebrahimirad** [comment]
Unfortunately I’m dealing with the same problem as you and I forced to delete the Tailwind from the project and use my own CSS framework. But right now again I have the problem on another project. please fix that issue.

**Comment by davodaslanifakor** [comment]
I found the solution for this version of tailwind set purge content like this
```
purge:{
    content: [
      "../../node_modules/@xxx-front/design-system/**/*.{js,vue,ts}"
   ]
}
```
and tailwind in nuxt.config add 
```
  tailwindcss: {
    jit: true,
    cssPath: '../config/tailwind/tailwind.scss',
    configPath: './tailwind.config.js',
  },
```
tailwind.scss content 
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
I find this option in content version +3 tailinwd.css and move into nuxt/tailwind by purge content.
In fact, tailwind need this patch to find and watch code in content for  compile

**Comment by davodaslanifakor** [comment]
@HuyAms  
Can share your `tailwind.config.js`

**Comment by HuyAms** [comment]
@davodaslanifakor Here you are

```
const defaultTheme = require("tailwindcss/defaultTheme")

module.exports = {
    content: ["./app/**/*.{ts,tsx,jsx,js}"],
    mode: process.env.NODE_ENV ? "jit" : undefined,
    theme: {
        screens: {
            sm: "640px",
            // => @media (min-width: 640px) { ... }

            md: "768px",
            // => @media (min-width: 768px) { ... }

            lg: "1024px",
            // => @media (min-width: 1024px) { ... }

            xl: "1280px",
            // => @media (min-width: 1280px) { ... }

            "2xl": "1536px",
            // => @media (min-width: 1536px) { ... }
        },
        fontSize: {
            xs: "14px",
            sm: "16px",
            base: "20px",
            lg: "24px",
            xl: "38px",
            "2xl": "48px",
            "3xl": "64px",
            "4xl": "76px",
        },
        colors: {
            // color scheme is defined in /app.css
            transparent: "transparent",
            current: "currentColor",
            white: "var(--color-white)",
            black: "var(--color-black)",
            blue: "var(--color-blue)",
            red: "var(--color-red)", // used for the <GridLines/>
            "blue-light": "var(--color-blue-light)",
            orange: "var(--color-orange)",
            gray: {
                20: "var(--color-gray-20)",
                60: "var(--color-gray-60)",
                100: "var(--color-gray-100)",
            },
        },
        extend: {
            spacing: {
                layout1: "16px",
                layout2: "24px",
                layout3: "32px",
                layout4: "48px",
                layout5: "64px",
                layout6: "96px",
                layout7: "160px",
            },
            fontFamily: {
                "sans-pro": [
                    "Source Sans Pro",
                    ...defaultTheme.fontFamily.sans,
                ],
                ubuntu: ["Ubuntu", ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [],
}
```

**Comment by davodaslanifakor** [comment]
@HuyAms You should your directory in `content` part match by your directory,
If you check my example code you will see.

**Comment by alireza-bonab** [comment]
The issue is related to the way Lerna handles script logs and redirects stdout from processes. `--stream` and `--parallel` arguments collect the output from single or multiple processes and then print them out and in `tailwind` CLI there is a weird implementation that checks stdout and if stdout is available it will continue the watch.
To solve this issue either you need to stop `--stream` and `--parallel` arguments with Lerna or find another way to call the script like using the `yarn workspace ...` command.

[https://github.com/tailwindlabs/tailwindcss/blob/122fb89e6c49a9d0d36c4fcdb57f9f2c39de7fc6/src/cli.js#L841](https://github.com/tailwindlabs/tailwindcss/blob/122fb89e6c49a9d0d36c4fcdb57f9f2c39de7fc6/src/cli.js#L841)

**Comment by pencilcheck** [comment]
i'm using nuxt, and using nuxt tailwind plugin @nuxtjs/tailwindcss, what would be the solution??

**Comment by pencilcheck** [comment]
> I found the solution for this version of tailwind set purge content like this
> 
> ```
> purge:{
>     content: [
>       "../../node_modules/@xxx-front/design-system/**/*.{js,vue,ts}"
>    ]
> }
> ```
> 
> and tailwind in nuxt.config add
> 
> ```
>   tailwindcss: {
>     jit: true,
>     cssPath: '../config/tailwind/tailwind.scss',
>     configPath: './tailwind.config.js',
>   },
> ```
> 
> tailwind.scss content
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 
> I find this option in content version +3 tailinwd.css and move into nuxt/tailwind by purge content. In fact, tailwind need this patch to find and watch code in content for compile

I am using the latest tailwind 3.x.x, I fixed it by simply adding the path to the dependent package content in content attr like so
```
module.exports = {
  important: true, // has !important for tailwind css
  content: [
    '../components/**/*.{js,ts,vue}',
    './layouts/**/*.{js,ts,vue}',
    './pages/**/*.{js,ts,vue}',
    './static/**/*.{html}',
    '../../node_modules/common/components/**/*.{js,ts,vue}',
    '../../node_modules/common/layouts/**/*.{js,ts,vue}',
    '../../node_modules/common/pages/**/*.{js,ts,vue}',
    '../../node_modules/common/static/**/*.{html}'
  ],
  presets: [],
  ...
}

```

If you use lerna to setup the monorepo dependencies, you actually can reference the files in your node_module in the mono repo root level, that's actually pretty cool lerna does that.
