### ISSUE TITLE
Cannot find module 'tailwind.config.js'

### ISSUE THREAD

**Issue by hanhdz025** [nuxt-community/tailwindcss-module#425]
### Version
@nuxtjs/tailwindcss: v5.0.0-2
nuxt: v3.0.0-27405623.a9ba1ca

output returns error when starting with nuxt3
![image](https://user-images.githubusercontent.com/20147479/153046041-0bf21d2e-8b2b-4f40-b611-25ea01026bad.png)

error occurred at line
`tailwindConfig = requireModule(configPath, { clearCache: true })`

when i overwrite the config path the problem was solved

`{
  tailwindcss: {
    configPath: '~/tailwind.config.js'
  }
}`

**Comment by pi0** [comment]
Thanks for the issue. Should be fixed in `5.0.0-3`
