### ISSUE TITLE
5.0.0-4 existing postcss config does not work with new defaults

### ISSUE THREAD

**Issue by loweoj** [nuxt-community/tailwindcss-module#433]
### Version
@nuxtjs/tailwindcss^5.0.0-4
"nuxt-edge": "latest"
"@nuxt/bridge": "npm:@nuxt/bridge-edge",

### Steps to reproduce
I have the following existing postcss config in my project:
```
postcss: {
      plugins: {
        "postcss-nested": {},
        autoprefixer: {},
      },
    },
```
The resultant postcss config after the defaults are merged is as follows:
```
{                                                                                                                                                                                      
  'postcss-nesting': {},
  'postcss-custom-properties': {},
  tailwindcss: { }, // ... my config 
  'postcss-nested': {},
  autoprefixer: {},
}
```

I get Tailwind warning me that:
"Nested CSS was detected, but CSS nesting has not been configured correctly. Please enable a CSS nesting plugin *before* Tailwind in your configuration. See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting"

So I see a few issues here:

1)  Is there a way to turn off your default config (remove ` 'postcss-nesting': {},  'postcss-custom-properties': {}` and use `postcss-nested` ?

2) How can I keep the plugin order correct to make sure Tailwind is happy with me?

I have a large codebase so refactoring all the css to use the `nesting` standard instead of the scss-compatible `nested` standard is not something I'm able to do right now.

I was struggling to get a codesandbox set up to show a reproduction - It kept crashing with 502 errors, so In left it. Hopefully the above info is enough to understand the issue. I can look further into a reproduction if necessary.

**Comment by Krillko** [comment]
I have perhaps the same problem, except I don't have any legacy codebase to consider.

"nuxt": "^2.15.8",
 "postcss": "^8.4.6",
"@nuxtjs/tailwindcss": "^5.0.0-4",

```
(91:3) Nested CSS was detected, but CSS nesting has not been configured correctly.
Please enable a CSS nesting plugin *before* Tailwind in your configuration.
```

I've looked at https://tailwindcss.com/docs/using-with-preprocessors#nesting, but nuxt documentation specificly says to not have a postcss.config.js

I've tried multiple combination in config, including 

```
 build: {
    transpile: [/typed-vuex/],
    postcss: {
      // Add plugin names as key and arguments as value
      // Install them before as dependencies with npm or yarn
      plugins: {
        'postcss-nested': false,
        'postcss-import': {},
        'tailwindcss/nesting': {},
        tailwindcss: {},
        autoprefixer: {},
      },
    },
  },
```

```
plugins: {
        'postcss-import': {},
        'tailwindcss/nesting': {},
        tailwindcss: {},
        autoprefixer: {},
        'postcss-nested': {},
      },
```

```
        'postcss-nested': false,
        'postcss-import': {},
        'tailwindcss/nesting': {},
        tailwindcss: {},
        autoprefixer: {},
        'postcss-nesting': {},
```

And serveral others.

**Comment by visualval** [comment]
this worked for me
```
  build: {
    postcss: {
      order: ['tailwindcss/nesting', 'tailwindcss', 'autoprefixer'],
      plugins: {
        "postcss-nested": false
      }
    },
},
```

**Comment by Krillko** [comment]
@visualval That worked for me too. Thanks.

**Comment by gion-f3** [comment]
Thanks @visualval for the fix!

**Comment by Almusamim** [comment]
This is not working with nuxt 3

**Comment by cerino-ligutom** [comment]
Using Nuxt3 latest here. Having the same issue as well and couldn't get the `tailwindcss/nesting` plugin to work.

![image](https://user-images.githubusercontent.com/6721822/157522201-33f48afa-e3b8-4859-b27d-6e4a5e5d3fe6.png)

Things I've tried but had no luck:

1. Adding the plugin as per [doc](https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#plugins) under the `postcss` key of the nuxt config.

```ts
export default defineNuxtConfig({
  // ...
  postcss: {
    plugins: {
      'tailwindcss/nesting': {}
    }
  }
  // ...
});
```

2. On the `build` key of the nuxt config as per @visualval's [comment](https://github.com/nuxt-community/tailwindcss-module/issues/433#issuecomment-1056791822). Probably only works on bridge?

> this worked for me
> 
> ```
>   build: {
>     postcss: {
>       order: ['tailwindcss/nesting', 'tailwindcss', 'autoprefixer'],
>       plugins: {
>         "postcss-nested": false
>       }
>     },
> },
> ```

3. Used a postcss config file. Probably ignored as it does nothing.

Has anyone managed to get it working on Nuxt3?

**Comment by jonathanjameswatson** [comment]
As a temporary fix on Nuxt 3 with Vite you can add the following module:

```ts
import type { Plugin } from 'postcss'

import { defineNuxtModule } from '@nuxt/kit'

const order = (names: Plugin[]) => {
  const tailwindNesting = names.splice(
    names.findIndex((plugin) => plugin.postcssPlugin === 'tailwindcss/nesting'),
    1
  )[0]
  names.unshift(tailwindNesting)
}

export default defineNuxtModule({
  hooks: {
    'vite:extend'({ config }) {
      order(config.css.postcss.plugins)
    },
  },
})
```

**Comment by yshrsmz** [comment]
@danielroe Hi, on Nuxt2, 5.0.1 still shows the same error for me.

5.0.0 with the workaround here worked fine.

with or without the workaround provided here, it shows 

```
Nested CSS was detected, but CSS nesting has not been configured correctly.Please enable a CSS nesting plugin *before* Tailwind in your configuration.See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting
```
