### ISSUE TITLE
JIT classes not working in nuxt3

### ISSUE THREAD

**Issue by jiblett1000** [nuxt-community/tailwindcss-module#439]
### Version

Operating System: Linux
Node Version: v16.14.0
Nuxt Version: 3.0.0-27428764.271289c
Package Manager: yarn@1.22.17
Bundler: Vite
User Config: build, css, buildModules
Runtime Modules: -
Build Modules: @pinia/nuxt@0.1.8, @nuxtjs/tailwindcss@5.0.0

### Reproduction Link

Not sure one is really necessary, but I am happy to add one if needed.

### What is actually happening?

nuxt3 v [3.0.0-27428764.271289c](https://www.npmjs.com/package/nuxt3/v/3.0.0-27428764.271289c) is the last working version for the tailwindcss module(v5.0.0). Something breaks after this version of nuxt and it seems JIT classes stop working. Posting this in the hope that it might help others and hopefully to find some better insight.

**Comment by vanling** [comment]
I think i got the same issue here. All classed are read and added once I restart `npm run dev`
Nothing fancy in the setup of nuxt.
```
export default defineNuxtConfig({
  buildModules: ["@nuxtjs/tailwindcss"],
  typescript: {
    shim: false,
  },
});
```

**Comment by jiblett1000** [comment]
This is working for me again with the latest packages. Could probably be closed.

**Comment by vanling** [comment]
Can't reproduce this anymore on clean build, still happens on my other application i am building, but maybe error on my side..

**Comment by jiblett1000** [comment]
I'm closing

**Comment by thiagorossener** [comment]
Hey guys, I'm using the latest Nuxt3 version [3.0.0-27487491.eb22ce9](https://www.npmjs.com/package/nuxt3) and it's still happening.

I can only use classes that are already in use, if I use a new class, I need to run `npm run dev` again.

Any ideas what I could do?

**Comment by vanling** [comment]
Got it happening to me again... just cant seem to find out where and how. I now include a `css: ['@/assets/css/tailwind.css'],` in nuxt.config.ts and just saving that assets/css/tailwind.css file "fixes" the missing jit classes for now. 

If i try a 100% clean repro build it does not happen.. Maybe only happens in larger (slower build) projects or somehow the jit content: [] is not working for for me. 

Will keep trying to find what causes this issue.

**Comment by Lehoczky** [comment]
Can confirm this still happens. When using new classes I sometimes have to restart the dev server to make them work.

**Comment by davidhellmann** [comment]
Same problem here 🤔

**Comment by hartmut-co-uk** [comment]
Same problem here 🤔

**Comment by Dari4sho** [comment]
What forked for me is adding all files with related markup to `tailwind.config.ts`, like:

```
  content: [
    "./components/**/*.{js,vue,ts}",
    "./composables/**/*.{js,vue,ts}",
    "./domains/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
```
