### ISSUE TITLE
Cannot read property 'tailwindcss/nesting' of undefined

### ISSUE THREAD

**Issue by Hutu-start** [nuxt-community/tailwindcss-module#440]
### Version
@nuxtjs/tailwindcss: 5.0.1
nuxt: 2.15.8

### What is actually happening?
Update to 5.0.1, nuxtjs may get the following ERROR when running or packaging: "Cannot read property 'tailwindcss/nesting' of undefined", I think in "main/src/module.ts(:101)", postcssOptions.plugins might be undefined

**Comment by vahid-bagh3ri** [comment]
I have the same problem !!

**Comment by danielroe** [comment]
Thanks! Should be resolved in 5.0.2. Let me know if not and I'll reopen.
