### ISSUE TITLE
Warn: Please enable a CSS nesting plugin *before* Tailwind in your configuration with Nuxt 3

### ISSUE THREAD

**Issue by adinvadim** [nuxt-community/tailwindcss-module#452]
### Version
@nuxtjs/tailwindcss: 5.0.0-4
nuxt3: latest

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-tatdgn?file=app.vue

### Steps to reproduce
1. Run
2. Look at console and see Warn

### What is Expected?
Console wihtout warn, because I added tailwind/nesting

### What is actually happening?
Warn

**Comment by productdevbook** [comment]
some problem

**Comment by RossComputerGuy** [comment]
I am having the same problem but its an error and not a warning

**Comment by vojtys** [comment]
same problem

**Comment by Atinux** [comment]
I updated your sandbox, it works perfectly without having to change any configuration: https://stackblitz.com/edit/nuxt-starter-jg7ufm?file=nuxt.config.ts,package.json,app.vue

We do support nesting by default with the module: https://github.com/nuxt-community/tailwindcss-module/blob/main/src/module.ts#L106-L109

**Comment by productdevbook** [comment]
> I updated your sandbox, it works perfectly without having to change any configuration: https://stackblitz.com/edit/nuxt-starter-jg7ufm?file=nuxt.config.ts,package.json,app.vue
> 
> We do support nesting by default with the module: https://github.com/nuxt-community/tailwindcss-module/blob/main/src/module.ts#L106-L109

![image](https://user-images.githubusercontent.com/38668796/171701447-f0c55261-7c8a-4c97-b2f1-60d56490f8ea.png)


https://github.com/productdevbook/productdevbook.com

dont fixed

**Comment by matifanger** [comment]
> > I updated your sandbox, it works perfectly without having to change any configuration: https://stackblitz.com/edit/nuxt-starter-jg7ufm?file=nuxt.config.ts,package.json,app.vue
> > We do support nesting by default with the module: https://github.com/nuxt-community/tailwindcss-module/blob/main/src/module.ts#L106-L109
> 
> ![image](https://user-images.githubusercontent.com/38668796/171701447-f0c55261-7c8a-4c97-b2f1-60d56490f8ea.png)
> 
> https://github.com/productdevbook/productdevbook.com/tree/old
> 
> dont fixed @Atinux

@productdevbook did you fixed it? how!

**Comment by 1714080902120** [comment]
Is there any solution? I meet this problem suddenly, after i reinstall dependencies some minutes ago...

**Comment by dhaladitya108** [comment]
> Is there any solution? I meet this problem suddenly, after i reinstall dependencies some minutes ago...
> 
> I found out my problem, i had add another dependencies, and it change the package.lock.json version, so even i delete the node_modules, it still no work.
> 
> Now it is work well after i delete package.lock.json and reinstall dependencies..

@1714080902120 tried the same didn't worked for me.

**Comment by ineshbose** [comment]
This shouldn't happen anymore. If you could share your nuxt configuration or reproduction please.

**Comment by ineshbose** [comment]
Odd. OK, I've made some changes if you'd like to test [nightly](https://tailwindcss.nuxtjs.org/getting-started/installation#nightly-releases) and confirm if it's working.

**Comment by ineshbose** [comment]
Odd. OK, I've made some changes if you'd like to test [nightly](https://tailwindcss.nuxtjs.org/getting-started/installation#nightly-releases) and confirm if it's working.
