### ISSUE TITLE
Fails running on latest nuxt3 version (nitropack RC1)

### ISSUE THREAD

**Issue by Rigo-m** [nuxt-community/tailwindcss-module#455]
### Version
@nuxtjs/tailwindcss: v5.0.2
nuxt: nuxt3 latest

### Reproduction Link
[test repo](https://github.com/Rigo-m/sb-nuxt-types-repro)

### Steps to reproduce
`yarn install && yarn dev`, node v16.14.2

### What is Expected?
Should work

### What is actually happening?
Tons of vite errors.

**Comment by Rigo-m** [comment]
@Atinux @danielroe pretty breaking bug

**Comment by danielroe** [comment]
I believe this goes away when you remove `nuxt.config` from your tailwind imports:

```diff
  module.exports = {
    content: {
      files: [
        './components/**/*.{vue,js}',
        './layouts/**/*.vue',
        './pages/**/*.vue',
        './app.vue',
        './plugins/**/*.{js,ts}',
-       "./nuxt.config.{js,ts}",
      ],
    },
  };
```

See https://stackblitz.com/edit/github-t2n64t?file=tailwind.config.js

**Comment by Rigo-m** [comment]
Opening a new issue

**Comment by vanling** [comment]
> I believe this goes away when you remove nuxt.config from your tailwind imports:

Yes, this worked!
