### ISSUE TITLE
Update config request 

### ISSUE THREAD

**Issue by Rigo-m** [nuxt-community/tailwindcss-module#456]
Update default config in [docs](https://tailwindcss.nuxtjs.org/tailwind/config), since it breaks vite build in nuxt3

**Comment by Atinux** [comment]
What do you mean it breaks vite build?

**Comment by Rigo-m** [comment]
@Atinux see: #455

**Comment by vanling** [comment]
@Atinux I think he means the default "content: []" config, i also just copied that and it broke the vite build, so I guess he is talking about removing `nuxt.config.{js,ts}` from the docs?

**Comment by Rigo-m** [comment]
@vanling correct!

**Comment by Rigo-m** [comment]
There's already a PR opened that references this issue
