### ISSUE TITLE
Color-adjust warnings

### ISSUE THREAD

**Issue by mihail727** [nuxt-community/tailwindcss-module#466]
### Version
@nuxtjs/tailwindcss: 5.0.3
nuxt: v3.0.0-rc.2-27525415.a8d42d5

### Reproduction Link
[Link](https://stackblitz.com/edit/nuxt-starter-d2hcad?file=app.vue)

### Steps to reproduce
just `yarn dev`

### What is Expected?
output in console: 
![](https://i.imgur.com/tkUP6iU.png)

### What is actually happening?
idk.... but it looks like this warning slows down hot reload
I also managed to find out that the matter is related to the plugin `tailwindcss/forms`- after installing it, this message appears

**Comment by alexigasse** [comment]
Hi, I've had the same issue yesterday. You can now update your `tailwindcss/forms` to v0.5.1 for fixing it. [Related issue](https://github.com/tailwindlabs/tailwindcss-forms/pull/115)
