### ISSUE TITLE
Does the module support arbitrary classes?

### ISSUE THREAD

**Issue by lisaschumann** [nuxt-community/tailwindcss-module#475]
Hi there! 

Is it possible to use arbitrary classes with nuxtjs/tailwindcss? It does not seem to work.

When I use class="h-full" it works, but class="h-[100px]" does not work. Am I missing something?

Thanks so much!

**Comment by jannikbuscha** [comment]
not for me :(

**Comment by DamianGlowala** [comment]
As much as the classes with arbitrary values do work for me (checked specifically the `h-[100px]` example), I noticed the corresponding CSS sometimes is and sometimes isn't generated. Restarting the development server works, but it still clearly is an issue to investigate.

**Comment by jannikbuscha** [comment]
> As much as the classes with arbitrary values do work for me (checked specifically the `h-[100px]` example), I noticed the corresponding CSS sometimes is and sometimes isn't generated. Restarting the development server works, but it still clearly is an issue to investigate.

for me these things don't work: arbitrary, :after !(important)
and that even after a dev-server restart

**Comment by Atinux** [comment]
Indeed it seems that we need to restart the server in order to work 🤔 

Any help on investigating it appreciated, maybe trying without the module?

**Comment by 1isten** [comment]
Enable JIT mode in `tailwind.config.js` works for me.

```js
// create tailwind.config.js in your project root directory

module.exports = {
  mode: 'jit',
  // ...
};
```

**Comment by larsdouweschuitema** [comment]
What node version are you using? I upgraded from node `14` to `16` and the arbitrary styles stopped working.
