### ISSUE TITLE
Release with dependencies fixed

### ISSUE THREAD

**Issue by KonradDeskiewicz** [nuxt-community/tailwindcss-module#479]
Can you please release the new version with the proper ufo `^0.8.4` version?
The latest release has version `0.7.11` that causes issues with Nuxt 3 RC3

Many thanks for considering my request.

**Comment by Atinux** [comment]
Can you test with the latest release: https://github.com/nuxt-community/tailwindcss-module/releases/tag/v5.1.2

**Comment by KonradDeskiewicz** [comment]
@Atinux Updated and all issues are gone. It looks fine IMHO :)
