### ISSUE TITLE
Upgrade to Tailwind 3.1

### ISSUE THREAD

**Issue by kristjanjansen** [nuxt-community/tailwindcss-module#490]
### Is your feature request related to a problem? Please describe.

Tailwindcss has a new 3.1 release https://tailwindcss.com/blog/tailwindcss-v3-1. It makes sense to upgrade.

### Describe the solution you'd like

Most of the code should work as is. Note that 3.1 provides version provides typings for the Tailwind config: https://tailwindcss.com/blog/tailwindcss-v3-1#first-party-type-script-types

### Describe alternatives you've considered

Keep it conservative and let the 3.1 mature.

### Additional context

https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md

**Comment by Atinux** [comment]
It’s up on https://github.com/nuxt-community/tailwindcss-module/releases/tag/v5.1.3
