### ISSUE TITLE
QUESTION  Intellisense in VS Code and custom CSS files. 

### ISSUE THREAD

**Issue by Serhioromano** [nuxt-community/tailwindcss-module#491]
This method works fine. But.

1. There is no intellisense in VS Code with tailwind extension. How to activate it?
2. It mentions support for CSS nesting, but how to I add css file that supports `@apply` and nesting?
3. It says it supports tailwind configuration but how? Just add `tailwind.config.js` file?

**Comment by Atinux** [comment]
1. It is activated once you have `tailwind.config.js` file in your project
2. Simply add CSS files in `assets/` directory and import them where needed (best is to you use `<style>` inside Vue components
3. Use `npx tailwindcss init`
