### ISSUE TITLE
Incomplete tailwind styling?

### ISSUE THREAD

**Issue by tlerbao** [nuxt-community/tailwindcss-module#495]
I use bg-slate-900 without any effect, but bg-gray-x is effective, why is this?

thanks

**Comment by brad-j** [comment]
I was looking for the exact same color just now.

**Comment by Atinux** [comment]
Can you try with 5.2.0?

**Comment by tlerbao** [comment]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/20442232/179328661-b0be27a6-f5d4-474e-97e6-4e8f64f7cd77.png">
@Atinux I tried to change @nuxtjs/tailwindcss to version 5.2.0, but it still doesn't work.

**Comment by hacknug** [comment]
@tlerbao do you have a reproduction repo?

**Comment by tlerbao** [comment]
Change to the installation method of the official website of tailwindcss, and the style is complete.
