### ISSUE TITLE
Recommended changes to DaisyUI example

### ISSUE THREAD

**Issue by marshallswain** [nuxt-community/tailwindcss-module#512]
### Is your feature request related to a problem? Please describe.

The [example DaisyUI implementation](https://tailwindcss.nuxtjs.org/examples/daisyui/) misses out on the ability to use the "system" setting for dark mode.  So it can't automatically switch between dark and light mode.  I'd make a PR to the docs, but the example is in a StackBlitz container.  I'd like to not have to research how to fix this in future projects, so I'd appreciate it if @Atinux could update the container with a couple of tweaks to enable system dark mode.

### Describe the solution you'd like

Update the `nuxt.config.ts` in the StackBlitz container to the following:

```ts
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss', '@nuxtjs/color-mode'],
  colorMode: {
    preference: 'system', // default theme
    dataValue: 'theme', // activate data-theme in <html> tag
    classSuffix: '',
  },
});
```

And add `'system'` to the themes in `app.vue`:

```vue
<template>
  <div class="p-4 flex gap-4">
    <button class="btn">Hello daisyUI</button>
    <select class="select w-full max-w-xs" v-model="colorMode.preference">
      <option disabled selected>Theme</option>
      <option v-for="theme of themes" :key="theme">{{ theme }}</option>
    </select>
  </div>
</template>

<script setup>
const colorMode = useColorMode();
const themes = [
  'system',
  'light',
  'dark',
  'cupcake',
  'bumblebee',
  'emerald',
  'corporate',
  'synthwave',
  'retro',
  'cyberpunk',
  'valentine',
  'halloween',
  'garden',
  'forest',
  'aqua',
  'lofi',
  'pastel',
  'fantasy',
  'wireframe',
  'black',
  'luxury',
  'dracula',
  'cmyk',
  'autumn',
  'business',
  'acid',
  'lemonade',
  'night',
  'coffee',
  'winter',
];
</script>
```

With the above changes, the `system` dark mode setting will be the default, and selecting a theme will override the system default, as expected.

**Comment by Atinux** [comment]
It's updated! https://stackblitz.com/edit/nuxt-color-mode-daisyui-snrnt9?file=app.vue

Thank you :blush:

**Comment by marshallswain** [comment]
Thank you!
