### ISSUE TITLE
[Regression Bug] - PurgeCSS stopped working after upgrade to v.1.3.0

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/tailwindcss-module#54]
Repro Link: https://codesandbox.io/s/happy-dijkstra-1ng86
How to reproduce:
- Create basic nuxt project
- add @nuxtjs/tailwind v.1.3.0
- yarn build

**Actual Result:** 
- PurgeCSS is broken. app.js file size - 740kb.

**Expected Result:** 
- PurgeCSS is working. app.js file size - 1kb.

Works as expected in 1.2.0

**Comment by Atinux** [comment]
Sorry about this, it's now fixed in [v1.3.1](https://github.com/nuxt-community/tailwindcss-module/releases/tag/v1.3.1)

**Comment by AndrewBogdanovTSS** [comment]
Tested with v.1.3.1 - resulting bundle became 740 times smaller! Nice! 😄👍
