### ISSUE TITLE
Styles and sizes are breaking on "npm generate".

### ISSUE THREAD

**Issue by rlam3** [nuxt-community/tailwindcss-module#58]
Styles and sizes are breaking on "npm generate". It serves up the pages fine in local "npm run dev".

Is there a workaround/solution? Or possibility something wrong with the build process inside this module??

**Comment by HoraceKeung** [comment]
Please take a look at this issue https://github.com/nuxt-community/tailwindcss-module/issues/55 and see if it is because some of the CSS are removed by PurgeCSS.

By default PurgeCSS is disabled in development environment, and when you run "npm generate" it generates the site in production environment with PurgeCSS enabled.

Normally CSS selectors from 3rd party libraries tend to be removed by PurgeCSS because the selectors are normally not directly used in your source code, and you will have to whitelist them.

**Comment by rlam3** [comment]
@HoraceKeung Thanks. But I'm really confused. Is purge css required to be used with this module? I set tailwindcss up with the npx nuxt project cli... and it didn't mention this in there. Nowhere was puge installed in the nuxt.config.js

```js
export default {
  mode: 'universal',
  /*
   ** Headers of the page
   */
  head: {
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      {
        hid: 'description',
        name: 'description',
        content: process.env.npm_package_description || ''
      }
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }]
  },
  /*
   ** Customize the progress-bar color
   */
  loading: { color: '#fff' },
  /*
   ** Global CSS
   */
  css: ['@fortawesome/fontawesome-svg-core/styles.css'],
  /*
   ** Plugins to load before mounting the App
   */
  plugins: ['~plugins/fontawesome'],
  /*
   ** Nuxt.js dev-modules
   */
  buildModules: [
    // Doc: https://github.com/nuxt-community/eslint-module
    '@nuxtjs/eslint-module',
    // Doc: https://github.com/nuxt-community/nuxt-tailwindcss
    '@nuxtjs/tailwindcss'
  ],
  tailwindcss: {
    configPath: '~/config/tailwind.config.js',
    cssPath: '~/assets/css/tailwind.css',
    purgeCSSInDev: true
  },
  /*
   ** Nuxt.js modules
   */
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    // Doc: https://github.com/nuxt-community/dotenv-module
    '@nuxtjs/dotenv'
  ],
  /*
   ** Axios module configuration
   ** See https://axios.nuxtjs.org/options
   */
  axios: {},
  /*
   ** Build configuration
   */
  build: {
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {}
  }
}

```

Where can I whitelist or how should I disable purge css for production? It just seems too much work to whitelist every individual tailwindcss class that I need to use. 

Thanks!

**Comment by HoraceKeung** [comment]
This module contains Tailwind and purgecss, which is a good thing, it suppose to set it all up for you already. You can disable purgecss but it is recommended to use it to removed unused CSS. Tailwind generates a lot of CSS utility classes and without purgecss, the final bundle will be large. https://tailwindcss.com/docs/controlling-file-size/#app

Please read my comment on https://github.com/nuxt-community/tailwindcss-module/issues/55
