### ISSUE TITLE
Feature Request: expose resolved Tailwind config within app

### ISSUE THREAD

**Issue by homerjam** [nuxt-community/tailwindcss-module#62]
I'm having a hard tie trying to access my Tailwind config in Nuxt in order to reference the breakpoints (screens) config ([related issue](https://github.com/tailwindcss/discuss/issues/50)).

It would be great if this module was able to provide the [resolved config](https://tailwindcss.com/docs/configuration#referencing-in-javascript) to avoid this issue.

**Comment by Atinux** [comment]
Actually it creates tailwind.config.js at the root of your directory ;)

**Comment by homerjam** [comment]
Indeed! But it seems it can't be imported because of the `import` / `module.exports` incompatibility. I've worked around it by importing in `nuxt.config.js` and storing as an `env` vars. However it'd be great to be avoid this boilerplate code and to have the resolved (full) config available.

**Comment by Atinux** [comment]
@homerjam could you make a reproduction by forking https://codesandbox.io/s/o4vn5pvp7q so I can better see what you are trying to achieve?

Please mention me so I can receive a notification

**Comment by homerjam** [comment]
Hi @Atinux 

https://codesandbox.io/s/nuxt-tailwindcss-import-config-example-ksgyc

**Comment by Atinux** [comment]
Hi @homerjam 

Could you try this?
https://tailwindcss.com/docs/configuration/#referencing-in-javascript

**Comment by homerjam** [comment]
@Atinux I've updated the sandbox. I did try that before but it seems like a problem with importing the config to begin with - the resolveConfig function combines the defaults with your own AFAIK.

**Comment by homerjam** [comment]
I also tried specifying `tailwind.config.js` in the `build.transpile` section of `nuxt.config`, but this didn't have any effect...

**Comment by Atinux** [comment]
Just found out this tweet: https://twitter.com/ClarkDu_/status/968885321017389056

We are investigating to find a workaround, also @pi0 told me that importing tailwind config resolver adds a lot of vendors:

![unknown](https://user-images.githubusercontent.com/904724/76335899-8076cb80-62f5-11ea-812e-284aa36d5cac.png)

So it may not be that good to actually import it in your Vue app 😬

**Comment by homerjam** [comment]
Ah ha! Although that tweet is quite an old one!

Noted - yes probably not worth importing the resolved config for my uses. Perhaps a better solution is to create a `tailwind.json` file with resolved config beside the `tailwind.css` file...?

**Comment by clarkdo** [comment]
Hi @homerjam , the TypeError you mentioned above will be fixed in https://github.com/nuxt/nuxt.js/pull/7070 .
After it's get merged, you can verify it by replacing `nuxt` with `nuxt-edge` and clearing `node_modules/.cache`

**Comment by Atinux** [comment]
@homerjam can you try with latest release of @nuxtjs/tailwindcss (v1.4.0) and try the `exposeConfig` option? https://github.com/nuxt-community/tailwindcss-module#referencing-in-javascript

Also, with new version of Nuxt.js it will be fixed also, two solutions for one problem 😄

**Comment by homerjam** [comment]
Thanks @Atinux ! It works great!

The only thing that I was wondering - could it use a path like `@/assets/tailwind.config.json`? I added a `/` after the `~` in the path by mistake which tripped me up, so maybe it would be for consistency it could be a bit more transparent?

**Comment by JLarky** [comment]
I would have been cautious to include `tailwind.config.js` as it might expose something you don't expect like `purge` option or add `@tailwindcss/ui` or some other plugins into your runtime.

I used a solution like this https://gist.github.com/JLarky/2d2591294e6c0215e0d3385fcd72af67 in app that I work on and I saved like **77kb** of gziped js bundle compared with requiring dynamic tailwind config.
