### ISSUE TITLE
how to enable and add autoprefixer? 

### ISSUE THREAD

**Issue by IsidroMar95** [nuxt-community/tailwindcss-module#68]
i need to add prefix but idk how enable or add PostCSS plugins to this config

**Comment by xabi93** [comment]
You only need to add to your nuxt.config.js file the following config:
```
  build: {
    postcss: {
      preset: {
        autoprefixer: {
          grid: true
        }
      }
    }
  }
```
As it says here: https://nuxtjs.org/api/configuration-build/#postcss autoprefixer package comes installed with nuxt

**Comment by IsidroMar95** [comment]
i did it , but i dont kow wich browser version is suported with this prefix ?
