### ISSUE TITLE
Warning unmet peer dependency on fresh install Webpack / purgecss

### ISSUE THREAD

**Issue by takburger-ap** [nuxt-community/tailwindcss-module#70]
On doing a fresh install, the following Warning is prompted.

`warning "@nuxtjs/tailwindcss > nuxt-purgecss > purgecss-webpack-plugin@1.6.0" has unmet peer dependency "webpack@^4 || ^3".`

I tried to add last webpack on the package.json without success even though nuxt already uses webpack.

**Comment by Atinux** [comment]
Try with `yarn upgrade` @takburger-ap

**Comment by takburger-ap** [comment]
My yarn was updated, retried on a new project after doing yarn upgrade just to be sure.

Still the same issue. Any idea ?

Here is my package.json 
`"dependencies": {
    "nuxt": "^2.11.0",
    "cross-env": "^5.2.0",
    "express": "^4.16.4"
  },
  "devDependencies": {
    "nodemon": "^1.18.9",
    "@nuxtjs/tailwindcss": "^1.0.0"
  }`

**Comment by michaeljakob** [comment]
`yarn add vue vuex`

**Comment by takburger-ap** [comment]
> try this: `yarn add vue vuex`

Thank you. I still have the issue after being prompt the following message :
`warning Pattern ["vuex@^3.2.0"] is trying to unpack in the same destination "/Users/user/Library/Caches/Yarn/v6/npm-vuex-3.2.0-86da7f26c3e131ff374870580109145a640ee5a8-integrity/node_modules/vuex" as pattern ["vuex@^3.1.3"]. This could result in non-deterministic behavior, skipping.`

I have no idea how to fix such issues. It makes me suppose the package was already there somehow. Isn't it ?
