### ISSUE TITLE
Class with "." in dev visible and production removed

### ISSUE THREAD

**Issue by Triloworld** [nuxt-community/tailwindcss-module#80]
This is example of how to reproduce in ```tailwind.config.js``` :

      fontSize: {
        '2.7xl': '1.75rem',
        '3.2xl': '2rem',
        '5.5xl': '3.5rem',
      },

Show when running "dev", in SSR mode (production) removed.
This need to fix by:
- error in dev mode to show that don't work
- fix in production mode by proper escape

**Comment by cannap** [comment]
try this 

extractor 
```
defaultExtractor: content => content.match(/[\w-/.:]+(?<!:)/g) || []
```
