### ISSUE TITLE
Should @apply work?

### ISSUE THREAD

**Issue by locopati** [nuxt-community/tailwindcss-module#83]
When I try to use @apply in my `main.scss` file, I get an error

> `@apply` cannot be used with `.hover\:bg-blue-700` because `.hover\:bg-blue-700` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.hover\:bg-blue-700` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

This is in `nuxt.config.js`
```
css: [
    '~assets/css/main.scss',
    '~assets/css/fonts.css'
  ],
  buildModules: [
    '@nuxtjs/tailwindcss'
  ],
```

I've also tried that css config array with `tailwind.css` at the start and end. Neither works.

`assets/css/tailwind.css` exists
```
/* purgecss start ignore */
@import 'tailwindcss/base';
@import 'tailwindcss/components';
/* purgecss end ignore */
@import 'tailwindcss/utilities';
```

Tailwind does work if I reference classes directly in my templates and pages, but that's an uglier solution (which could be lessened by components, but still less pleasing than having everything referred to from SCSS files.

Curious if there's any way to make this work. Thank you.

**Comment by locopati** [comment]
I also tried pulling the tailwind @import statements into `main.scss` and that didn't work either.

**Comment by Atinux** [comment]
Actually you have to use:

```postcss
.my-class {
  @apply bg-blue-700;
}
.my-class :hover {
  @apply bg-blue-500;
}
```
