### ISSUE TITLE
Explain on Readme.md file this module is the same as choosing tailwindcss when using npx create-nuxt-app

### ISSUE THREAD

**Issue by lmuzquiz** [nuxt-community/tailwindcss-module#84]
Maybe it's a stupid comment. But I thought for like an hour that somehow this repo was something different than what i previously had by setting up a tailwindcss app using npx create-nuxt-app You could just add a big line somewhere on the readme.md file clarifying that.

**Comment by Atinux** [comment]
HI @lmuzquiz 

We are going to change the way `create-nuxt-app` works so it will be clearer in the future :)
