### ISSUE TITLE
How yo update tailwindcss?

### ISSUE THREAD

**Issue by mahmoudmy** [nuxt-community/tailwindcss-module#88]
I need to update **tailwindcss** to it's new version?
Is this enough?
```
npm install tailwindcss@latest
```

**Comment by yohan-atlan** [comment]
I am interested too !

**Comment by Atinux** [comment]
You can install latest version of `@nuxtjs/tailwindcss`, see https://github.com/nuxt-community/tailwindcss-module/releases/tag/v1.4.1
