### ISSUE TITLE
Nuxt not loading other CSS Frameworks while @nuxtjs/tailwindcss is on buildModules

### ISSUE THREAD

**Issue by edmbn** [nuxt-community/tailwindcss-module#89]
I tried to load Bootstrap components together with Tailwindcss. When working on **dev** mode all works fine but when I run **yarn generate** resulting files don't load other styles apart from Tailwind ones. When commenting **"@nuxtjs/tailwindcss"** from **buildModules** on **nuxt.config.js** and generating static website again with **yarn generate** all Bootstrap styles load fine. 

Bootstrap **without** styles after **yarn generate**:

```
buildModules: [
    // Doc: https://github.com/nuxt-community/nuxt-tailwindcss
    "@nuxtjs/tailwindcss"
  ],
```

Bootstrap **with** styles after **yarn generate**:

```
buildModules: [
    // Doc: https://github.com/nuxt-community/nuxt-tailwindcss
   // "@nuxtjs/tailwindcss"
  ],
```

Again all of this in **dev** mode is working fine, it is just a problem when running **yarn generate**

Steps to reproduce: 

1 - Create new nuxt app with **yarn create nuxt-app** selecting Tailwindcss as CSS Framework. 
2 - Install bootstrap and and bootstrap-vue as told on: https://bootstrap-vue.js.org/docs/#nuxtjs-module

Repository: https://github.com/edmbn/issue-nuxt-tailwind-bootstrap

Thank you for your time.

**Comment by Atinux** [comment]
I think this is due to `purgeCSS` that remove your bootstrap classes.

Try to update your purgeCSS options:
`nuxt.config.js`
```js
export default {
  purgeCSS: {
    enabled: false
  }
}
```

**Comment by edmbn** [comment]
Yes... It was that. Thank you so much. 

I know it isn't recommended but in my case I just want to load a single component from Bootstrap because of its by default logic (data table).  There should be a way to combine without loading all of this CSS, right?

**Comment by Atinux** [comment]
There is no real solution right now, we are in discussion with BootstrapVue team to imagine something that could mix both Bootstrap and TailwindCSS for theming. It is not biggest priority now since Vue 3 is :)

**Comment by bramburn** [comment]
use the SCSS import of that bootstrap variable and the _tables


Regards,


B.Ramburn BSc LLM#
Snr. Quantity Surveyor
