### ISSUE TITLE
Tailwind 1.4 with purgeCSS included

### ISSUE THREAD

**Issue by sausin** [nuxt-community/tailwindcss-module#94]
Hello,

Thanks for maintaining this package! Would be awesome to have some suggestions included on handling 1.4 release with Nuxt.js now that purgeCSS has been included inside tailwindcss.

Thanks!
Saurabh

**Comment by Atinux** [comment]
Hi,

Will work on it this week :)

**Comment by sausin** [comment]
Great! Thanks a lot :smiley:

**Comment by davidsneal** [comment]
+1 for the spacing utilities too :) https://tailwindcss.com/docs/space/#app

**Comment by sausin** [comment]
2.0 seems to work just fine - thanks a lot for the super quick update :-)

Also, looking forward to the implementation of the work around vite with nuxtjs :+1:
